/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/uploads/{id}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The owning account can read processing state for a resumable upload. */
        get: operations["getNodoUploadMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/media/{id}/referenced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Internal Nodo cleanup gate. A missing or invalid response must preserve the file. */
        get: operations["isNodoMediaReferenced"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or refresh the local account projection for an authenticated user. */
        post: operations["bootstrapSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fluo/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFluoPosts"];
        put?: never;
        post: operations["createFluoPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fluo/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getFluoPost"];
        put?: never;
        post?: never;
        delete: operations["deleteFluoPost"];
        options?: never;
        head?: never;
        patch: operations["setFluoPostVisibility"];
        trace?: never;
    };
    "/v1/fluo/posts/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFluoComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fluo/posts/{id}/saved": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["saveFluoPost"];
        post?: never;
        delete: operations["unsaveFluoPost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fluo/posts/{id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setFluoReaction"];
        post?: never;
        delete: operations["clearFluoReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fluo/users/{id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["followFluoUser"];
        post?: never;
        delete: operations["unfollowFluoUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchLigoUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLigoConversations"];
        put?: never;
        post: operations["createLigoConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLigoConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addLigoMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLigoMessages"];
        put?: never;
        post: operations["sendLigoMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLigoMessage"];
        options?: never;
        head?: never;
        patch: operations["editLigoMessage"];
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/messages/{messageId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setLigoReaction"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/delivered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markLigoDelivered"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/conversations/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markLigoRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ligo/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Short-lived SSE change hints scoped to the authenticated account. Reconnect after the stream closes. */
        get: operations["streamLigoEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRondoServers"];
        put?: never;
        post: operations["createRondoServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["discoverRondoServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRondoServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinRondoServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteRondoMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers/{id}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["leaveRondoServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/servers/{id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRondoChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rondo/channels/{id}/voice-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRondoVoiceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegadoSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegadoUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setRegadoUserStatus"];
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegadoAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Audited administrator role change. Self changes and granting admin to disabled accounts are rejected. */
        patch: operations["setRegadoUserRole"];
        trace?: never;
    };
    "/v1/admin/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Opens a 15-minute account-content access case, audits it and notifies the target in Ligo Saved messages. */
        post: operations["openRegadoAccessCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cases/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Audited content read for the case creator before expiry. Media URLs expire after one minute. */
        get: operations["readRegadoCaseContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cases/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ends the case immediately and audits it. Previously issued media links expire within one minute. */
        post: operations["closeRegadoAccessCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegadoSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegadoMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegadoLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/logs/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Audits and persists host-wide journal retention. Archived journals may be deleted by native rotation and vacuum. */
        patch: operations["setRegadoLogRetention"];
        trace?: never;
    };
    "/v1/admin/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runRegadoAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/storage/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewRegadoStoragePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/storage/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyRegadoStoragePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserIdentity: {
            /**
             * Format: uuid
             * @description Kaordo UUIDv7; distinct from the Keycloak subject.
             */
            id: string;
            username: string;
            displayName: string;
            /** Format: date-time */
            createdAt: string;
            isAdmin: boolean;
        };
        ApiError: {
            error: string;
            /** @description A stable, non-sensitive reason when an authentication request is rejected. */
            code?: string;
        };
        RegadoSummary: {
            users: number;
            posts: number;
            messages: number;
            uploads: number;
            mediaBytes: number;
            databaseBytes: number;
            openCases: number;
            mediaByKind: {
                kind: string;
                objects: number;
                bytes: number;
            }[];
        };
        RegadoUser: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            isAdmin: boolean;
            /** Format: date-time */
            disabledAt: string | null;
            postCount: number;
            messageCount: number;
            mediaBytes: number;
            /** Format: date-time */
            lastActivity: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        RegadoAuditEntry: {
            /** Format: uuid */
            id: string;
            actor: string;
            target: string | null;
            action: string;
            reason: string;
            detail: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        RegadoCase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            targetUserId: string;
            targetUsername: string;
            reason: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        RegadoContentMedia: {
            /** Format: uuid */
            id: string;
            kind: string;
            mimeType: string;
            filename: string;
            size: number;
            /** Format: uri */
            url: string;
        };
        RegadoContent: {
            /** Format: uuid */
            id: string;
            text: string;
            context: string;
            /** Format: date-time */
            createdAt: string;
            media: components["schemas"]["RegadoContentMedia"][];
        };
        RegadoContentPage: {
            items: components["schemas"]["RegadoContent"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        RegadoDisk: {
            name: string;
            path: string;
            label: string | null;
            partitionLabel: string | null;
            fsType: string | null;
            size: number;
            type: string;
            model: string | null;
            serial: string | null;
            wwn: string | null;
            mountpoints: (string | null)[];
            /** @description Whether this device contains the filesystem mounted at / */
            systemDisk: boolean;
            /**
             * @description Operational state of this physical device in the managed storage pool
             * @enum {string}
             */
            storageState?: "unconfigured" | "queued" | "working";
            /** @description Whether the host agent's current preflight considers this device safe to onboard */
            configureEligible?: boolean;
            /** @description A concise explanation of the current storage state or onboarding eligibility */
            configureReason?: string;
            /** @description Discovered physical connection such as SATA */
            transport?: string | null;
            /** @description Discovered controller address; no enclosure bay is inferred */
            address?: string | null;
            partitionType?: string | null;
            start?: number;
            number?: number;
            /** @enum {string} */
            role?: "" | "system" | "storage" | "unassigned";
            bootKind?: string;
            /** @description Partition-table and alignment slack excluded from allocatable regions */
            overheadBytes?: number;
            layoutAvailable?: boolean;
            unallocated?: {
                /** @description Byte offset from the start of the physical disk */
                start: number;
                size: number;
            }[];
            children?: components["schemas"]["RegadoDisk"][];
            health?: components["schemas"]["RegadoDiskHealth"];
        };
        RegadoDiskHealth: {
            /** @enum {string} */
            state: "passed" | "warning" | "failed" | "unavailable" | "standby";
            passed: boolean | null;
            temperatureC: number | null;
            powerOnHours: number | null;
            reallocatedSectors: number | null;
            pendingSectors: number | null;
            uncorrectableSectors: number | null;
            /** Format: date-time */
            checkedAt: string;
        };
        RegadoMount: {
            path: string;
            source: string;
            fsType: string;
            total: number;
            used: number;
            free: number;
            available: boolean;
            integrity: components["schemas"]["RegadoFilesystemIntegrity"] | null;
        };
        RegadoFilesystemIntegrity: {
            uuid: string;
            /** @description Physical block device paths participating in this Btrfs filesystem */
            members: string[];
            dataProfile: string;
            metadataProfile: string;
            systemProfile: string;
            mirroredPercent: number;
            deviceErrors: number;
            devicesOnline: number;
            devicesExpected: number;
            healthy: boolean;
            balanceRunning: boolean;
            /** @enum {string} */
            scrubState: "not-run" | "running" | "complete" | "errors" | "unknown";
            scrubErrors: number;
            /** @description Sum of physical pool capacity before RAID replication */
            physicalTotal?: number;
            /** @description Physical space used including replicas and metadata */
            physicalUsed?: number;
        };
        RegadoReplicationReport: {
            path: string;
            /** @enum {string} */
            state: "checking" | "repairing" | "complete" | "failed";
            /** @enum {string} */
            stage: "replication" | "checksums" | "inventory" | "complete";
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            checkedAt: string | null;
            files: number;
            /** @description Logical size of regular files */
            bytes: number;
            unreadable: number;
            /** @enum {string} */
            duplication: "" | "duplicated" | "single" | "unverified";
            progress?: components["schemas"]["RegadoOperationProgress"] | null;
            /** @enum {string} */
            checksumState: "" | "passed" | "errors";
            error: string;
        };
        RegadoOperationProgress: {
            completed: number;
            /** @description Null when no measured denominator is available */
            total: number | null;
            /** @enum {string} */
            unit: "bytes" | "chunks" | "files" | "uploads" | "steps";
        };
        RegadoLayoutRequest: {
            device: string;
            identity: string;
            filesystem: string;
            systemBytes: number;
            storageBytes: number;
            fingerprint?: string;
            confirmation?: string;
        };
        RegadoLayoutStep: {
            /** @enum {string} */
            kind: "keep" | "boot" | "create" | "resize" | "activate";
            /** @enum {string} */
            role: "system" | "storage";
            number: number;
            start: number;
            size: number;
            previousSize: number;
            source: string;
        };
        RegadoStoragePlan: {
            device: string;
            identity: string;
            fingerprint: string;
            supported: boolean;
            /** @enum {string} */
            backend: "disko" | "systemd-repart";
            /** @description Exportable Disko role declaration; applying it to existing disks requires operator review */
            declaration: string;
            issues: string[];
            warnings: string[];
            systemBytes: number;
            storageBytes: number;
            availableBytes: number;
            steps: components["schemas"]["RegadoLayoutStep"][];
        };
        RegadoLayoutReport: {
            device: string;
            /** @enum {string} */
            state: "running" | "complete" | "failed";
            stage: string;
            /** Format: date-time */
            startedAt: string;
            error: string;
            progress: components["schemas"]["RegadoOperationProgress"] | null;
        };
        RegadoMediaMaintenance: {
            directory: string;
            /** @enum {string} */
            state: "idle" | "checking" | "repairing" | "complete" | "failed";
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            checkedAt: string | null;
            files: number;
            bytes: number;
            /** @description Actual expired upload artifact files with no database references */
            surplusFiles: number;
            surplusBytes: number;
            unverifiedFiles: number;
            missingFiles: number;
            removedFiles: number;
            removedBytes: number;
            error: string;
            /** @enum {string} */
            stage?: "" | "inventory" | "references" | "complete";
            progress?: components["schemas"]["RegadoOperationProgress"] | null;
        };
        RegadoSwapDevice: {
            name: string;
            path: string;
            /** @enum {string} */
            kind: "compressed RAM" | "disk swap" | "swap file";
            size: number;
            used: number;
            priority: number;
        };
        RegadoActionResult: {
            action: string;
            target: string;
            output: string;
            accepted: boolean;
        };
        RegadoService: {
            id: string;
            active: string;
            substate: string;
            loaded: string;
            type?: string;
            result?: string;
            exitCode?: number;
            /** Format: date-time */
            finishedAt?: string;
            timer?: {
                id: string;
                active: string;
                substate: string;
                /** Format: date-time */
                lastRunAt: string | null;
                /** Format: date-time */
                nextRunAt: string | null;
            };
        };
        RegadoSystem: {
            hostname: string;
            host: {
                cpuModel: string;
                logicalCores: number;
                memoryTotalBytes: number;
                uptimeSeconds: number;
                kernel: string;
                osName?: string;
                osVersion?: string;
                /** @enum {string} */
                bootMode?: "bios" | "uefi";
            };
            /** Format: date-time */
            time: string;
            disks: components["schemas"]["RegadoDisk"][];
            mounts: components["schemas"]["RegadoMount"][];
            swapDevices: components["schemas"]["RegadoSwapDevice"][];
            services: components["schemas"]["RegadoService"][];
            layoutReports?: components["schemas"]["RegadoLayoutReport"][];
            replicationReports?: components["schemas"]["RegadoReplicationReport"][];
            mediaMaintenance?: components["schemas"]["RegadoMediaMaintenance"] | null;
        };
        RegadoSample: {
            time: number;
            value: number;
        };
        RegadoMetrics: {
            /** @enum {string} */
            window: "1h" | "24h" | "7d";
            series: {
                [key: string]: components["schemas"]["RegadoSample"][];
            };
        };
        RegadoLogs: {
            service: string;
            journal?: components["schemas"]["RegadoJournal"];
            items: {
                time: string;
                priority: string;
                message: string;
            }[];
        };
        RegadoJournal: {
            totalBytes: number | null;
            diskBytes: number | null;
            runtimeBytes: number | null;
            maxUseBytes: number | null;
            retentionDays: number | null;
            managed: boolean;
            warning?: string;
        };
        LigoUser: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
        };
        LigoMedia: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "image" | "video" | "file";
            mimeType: string;
            filename: string;
            width: number;
            height: number;
            /** Format: int64 */
            size: number;
            altText: string;
            /** Format: uri */
            url: string;
        };
        LigoReaction: {
            /** @enum {string} */
            emoji: "❤️" | "👍" | "👎";
            count: number;
            mine: boolean;
        };
        LigoMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            clientId: string;
            sender: components["schemas"]["LigoUser"];
            text: string;
            media: components["schemas"]["LigoMedia"][];
            reactions: components["schemas"]["LigoReaction"][];
            /** @enum {string} */
            status: "sent" | "delivered" | "read";
            /** Format: date-time */
            editedAt: string | null;
            deleted: boolean;
            systemNotice: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        LigoMessagePreview: {
            /** Format: uuid */
            id: string;
            text: string;
            /** Format: uuid */
            senderId: string;
            deleted: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        LigoConversation: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "duo" | "group" | "self" | "channel";
            title: string;
            /** Format: uuid */
            createdBy: string;
            members: components["schemas"]["LigoUser"][];
            lastMessage: components["schemas"]["LigoMessagePreview"] | null;
            unreadCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LigoConversationPage: {
            items: components["schemas"]["LigoConversation"][];
            nextCursor: string | null;
        };
        LigoUserPage: {
            items: components["schemas"]["LigoUser"][];
        };
        LigoMessagePage: {
            items: components["schemas"]["LigoMessage"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        LigoNewConversation: {
            /** @enum {string} */
            kind: "duo" | "group" | "self";
            title?: string;
            participantIds: string[];
        };
        LigoNewMessage: {
            /** Format: uuid */
            clientId: string;
            text: string;
            attachmentIds?: string[];
            altTexts?: {
                [key: string]: string;
            };
        };
        LigoReadRequest: {
            /** Format: uuid */
            messageId: string;
        };
        LigoEditMessageRequest: {
            text: string;
        };
        LigoReactionRequest: {
            /** @enum {string} */
            emoji: "❤️" | "👍" | "👎";
            active: boolean;
        };
        LigoMembersRequest: {
            participantIds: string[];
        };
        RondoServer: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @enum {string} */
            access: "public" | "private";
            /** Format: uuid */
            ownerId: string;
            memberCount: number;
            joined: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        RondoChannel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            serverId: string;
            /** Format: uuid */
            conversationId: string;
            name: string;
            position: number;
            /** Format: date-time */
            createdAt: string;
        };
        RondoDetail: {
            server: components["schemas"]["RondoServer"];
            channels: components["schemas"]["RondoChannel"][];
            /** @description The first 100 members, ordered by join time. */
            members: components["schemas"]["LigoUser"][];
        };
        RondoServerPage: {
            items: components["schemas"]["RondoServer"][];
        };
        RondoNewServer: {
            name: string;
            description: string;
            /** @enum {string} */
            access: "public" | "private";
        };
        RondoInvite: {
            /** Format: uuid */
            userId: string;
        };
        RondoNewChannel: {
            name: string;
        };
        RondoVoiceTicket: {
            /** Format: uri */
            serverUrl: string;
            participantToken: string;
        };
        /** @description Tiptap JSON document. Only paragraphs, text, line breaks and bold/italic/strike marks are accepted. */
        FluoDocument: {
            /** @constant */
            type: "doc";
            content: {
                [key: string]: unknown;
            }[];
        };
        FluoAuthor: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            following: boolean;
        };
        FluoMedia: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "image" | "video";
            mimeType: string;
            width: number;
            height: number;
            /** Format: int64 */
            size: number;
            /** @description Description for assistive technology */
            altText: string;
            /**
             * Format: uri
             * @description Short lived signed Nodo URL.
             */
            url: string;
        };
        FluoQuote: {
            /** Format: uuid */
            id: string;
            author: components["schemas"]["FluoAuthor"];
            text: string;
            media: components["schemas"]["FluoMedia"][];
        };
        FluoCounts: {
            /** Format: int64 */
            good: number;
            /** Format: int64 */
            bad: number;
            /** Format: int64 */
            comments: number;
        };
        FluoPost: {
            /** Format: uuid */
            id: string;
            author: components["schemas"]["FluoAuthor"];
            content: components["schemas"]["FluoDocument"];
            text: string;
            /** @enum {string} */
            visibility: "public" | "private";
            /** Format: uuid */
            parentId: string | null;
            /** Format: uuid */
            quoteId: string | null;
            quote: components["schemas"]["FluoQuote"] | null;
            media: components["schemas"]["FluoMedia"][];
            counts: components["schemas"]["FluoCounts"];
            /** @enum {string|null} */
            myReaction: "good" | "bad" | null;
            /** @description Whether the current user saved this post. */
            saved: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FluoPage: {
            items: components["schemas"]["FluoPost"][];
            nextCursor: string | null;
        };
        FluoNewPost: {
            content: components["schemas"]["FluoDocument"];
            /** @enum {string} */
            visibility: "public" | "private";
            /** Format: uuid */
            parentId?: string;
            /** Format: uuid */
            quoteId?: string;
            attachmentIds?: string[];
            /** @description Optional descriptions keyed by attached upload ID; stored per post. */
            altTexts?: {
                [key: string]: string;
            };
        };
        FluoPostVisibility: {
            /** @enum {string} */
            visibility: "public" | "private";
        };
        FluoReaction: {
            /** @enum {string} */
            value: "good" | "bad";
        };
        NodoUpload: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "image" | "video" | "file";
            mimeType: string;
            filename: string;
            width: number;
            height: number;
            /** Format: int64 */
            size: number;
            complete: boolean;
        };
        MediaReference: {
            referenced: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNodoUploadMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processed upload metadata, ready for an authorized application reference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoUpload"];
                };
            };
            /** @description Upload or media processing is not complete. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid, expired, failed or inaccessible upload. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    isNodoMediaReferenced: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current database reference state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaReference"];
                };
            };
            /** @description The reference state could not be checked. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is available. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bootstrapSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable Kaordo identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIdentity"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Kaordo identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIdentity"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Account projection has not been created yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listFluoPosts: {
        parameters: {
            query?: {
                feed?: "latest" | "following" | "mine" | "saved";
                /** @description Search post text and author names */
                q?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible root posts in reverse chronological order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPage"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createFluoPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FluoNewPost"];
            };
        };
        responses: {
            /** @description Created post. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPost"];
                };
            };
            /** @description Validation, access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getFluoPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPost"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteFluoPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted own post and its comments. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setFluoPostVisibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FluoPostVisibility"];
            };
        };
        responses: {
            /** @description Updated post visibility. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation, access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listFluoComments: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible direct comments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPage"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    saveFluoPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved the accessible post to the current user's private list. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    unsaveFluoPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed the post from the current user's saved list. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setFluoReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FluoReaction"];
            };
        };
        responses: {
            /** @description Updated post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPost"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    clearFluoReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluoPost"];
                };
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    followFluoUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followed user. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    unfollowFluoUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unfollowed user. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access or server error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    searchLigoUsers: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching Kaordo accounts other than the viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoUserPage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listLigoConversations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversations containing the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoConversationPage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createLigoConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoNewConversation"];
            };
        };
        responses: {
            /** @description New or existing direct conversation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoConversation"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getLigoConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessible conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoConversation"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addLigoMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoMembersRequest"];
            };
        };
        responses: {
            /** @description Group with newly added members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoConversation"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listLigoMessages: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first, older pages use nextCursor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoMessagePage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sendLigoMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoNewMessage"];
            };
        };
        responses: {
            /** @description Sent or idempotently replayed message. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoMessage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteLigoMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                messageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message content removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    editLigoMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                messageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoEditMessageRequest"];
            };
        };
        responses: {
            /** @description Edited message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoMessage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setLigoReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                messageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoReactionRequest"];
            };
        };
        responses: {
            /** @description Message with updated reactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LigoMessage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    markLigoDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoReadRequest"];
            };
        };
        responses: {
            /** @description Delivery position updated after receipt by an active client. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    markLigoRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LigoReadRequest"];
            };
        };
        responses: {
            /** @description Read position updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    streamLigoEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream with ready, update and resync events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRondoServers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servers joined by the authenticated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoServerPage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createRondoServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RondoNewServer"];
            };
        };
        responses: {
            /** @description Server with its default general channel. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoDetail"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    discoverRondoServers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public servers that the authenticated account has not joined. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoServerPage"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRondoServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server channels and members, visible to members only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoDetail"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    joinRondoServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership and channel access established for a public server. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoDetail"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    inviteRondoMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RondoInvite"];
            };
        };
        responses: {
            /** @description Updated server membership; owner only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoDetail"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    leaveRondoServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createRondoChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RondoNewChannel"];
            };
        };
        responses: {
            /** @description New channel with message history and voice room access for current members. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoChannel"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createRondoVoiceToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short lived LiveKit token for one channel voice room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RondoVoiceTicket"];
                };
            };
            /** @description Error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRegadoSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product counts for an administrator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRegadoUsers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 matching accounts and their usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RegadoUser"][];
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setRegadoUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled: boolean;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRegadoAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest 100 administrator audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RegadoAuditEntry"][];
                    };
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setRegadoUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isAdmin: boolean;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    openRegadoAccessCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    targetUserId: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Opened case */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoCase"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readRegadoCaseContent: {
        parameters: {
            query: {
                kind: "posts" | "messages";
                before?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 50 content items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoContentPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    closeRegadoAccessCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRegadoSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local host */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoSystem"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRegadoMetrics: {
        parameters: {
            query: {
                window: "1h" | "24h" | "7d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus time series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoMetrics"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRegadoLogs: {
        parameters: {
            query: {
                service: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest journal entries for an allowlisted service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoLogs"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setRegadoLogRetention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Zero keeps history until the storage budget requires rotation
                     * @enum {integer}
                     */
                    retentionDays: 0 | 1 | 7 | 14 | 30 | 90;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Applied journal policy and current host-wide usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoJournal"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    runRegadoAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: "restart-nodo" | "restart-livekit" | "restart-ddclient" | "scrub-filesystem" | "configure-storage" | "check-storage" | "repair-storage";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                    /** @description Device path for configure-storage or mounted Btrfs path for scrub-filesystem/check-storage/repair-storage */
                    target?: string;
                    /** @description Stable serial or WWN */
                    identity?: string;
                    /** @description Existing mounted Btrfs data-pool path for configure-storage */
                    filesystem?: string;
                };
            };
        };
        responses: {
            /** @description Audited system operation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoActionResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    previewRegadoStoragePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegadoLayoutRequest"];
            };
        };
        responses: {
            /** @description Non-mutating layout preview with capability constraints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoStoragePlan"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    applyRegadoStoragePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegadoLayoutRequest"] & {
                    reason: string;
                    fingerprint: string;
                    confirmation: string;
                };
            };
        };
        responses: {
            /** @description Revalidated audited layout change queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegadoActionResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
