//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AdminAudit = newAdminAuditTable("public", "admin_audit", "")

type adminAuditTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	ActorID      postgres.ColumnString
	TargetUserID postgres.ColumnString
	Action       postgres.ColumnString
	Reason       postgres.ColumnString
	Detail       postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AdminAuditTable struct {
	adminAuditTable

	EXCLUDED adminAuditTable
}

// AS creates new AdminAuditTable with assigned alias
func (a AdminAuditTable) AS(alias string) *AdminAuditTable {
	return newAdminAuditTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AdminAuditTable with assigned schema name
func (a AdminAuditTable) FromSchema(schemaName string) *AdminAuditTable {
	return newAdminAuditTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AdminAuditTable with assigned table prefix
func (a AdminAuditTable) WithPrefix(prefix string) *AdminAuditTable {
	return newAdminAuditTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AdminAuditTable with assigned table suffix
func (a AdminAuditTable) WithSuffix(suffix string) *AdminAuditTable {
	return newAdminAuditTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAdminAuditTable(schemaName, tableName, alias string) *AdminAuditTable {
	return &AdminAuditTable{
		adminAuditTable: newAdminAuditTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newAdminAuditTableImpl("", "excluded", ""),
	}
}

func newAdminAuditTableImpl(schemaName, tableName, alias string) adminAuditTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		ActorIDColumn      = postgres.StringColumn("actor_id")
		TargetUserIDColumn = postgres.StringColumn("target_user_id")
		ActionColumn       = postgres.StringColumn("action")
		ReasonColumn       = postgres.StringColumn("reason")
		DetailColumn       = postgres.StringColumn("detail")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, ActorIDColumn, TargetUserIDColumn, ActionColumn, ReasonColumn, DetailColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{ActorIDColumn, TargetUserIDColumn, ActionColumn, ReasonColumn, DetailColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, ReasonColumn, DetailColumn, CreatedAtColumn}
	)

	return adminAuditTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ActorID:      ActorIDColumn,
		TargetUserID: TargetUserIDColumn,
		Action:       ActionColumn,
		Reason:       ReasonColumn,
		Detail:       DetailColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
