//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AdminAccessCases = newAdminAccessCasesTable("public", "admin_access_cases", "")

type adminAccessCasesTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	ActorID      postgres.ColumnString
	TargetUserID postgres.ColumnString
	Reason       postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	ExpiresAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AdminAccessCasesTable struct {
	adminAccessCasesTable

	EXCLUDED adminAccessCasesTable
}

// AS creates new AdminAccessCasesTable with assigned alias
func (a AdminAccessCasesTable) AS(alias string) *AdminAccessCasesTable {
	return newAdminAccessCasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AdminAccessCasesTable with assigned schema name
func (a AdminAccessCasesTable) FromSchema(schemaName string) *AdminAccessCasesTable {
	return newAdminAccessCasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AdminAccessCasesTable with assigned table prefix
func (a AdminAccessCasesTable) WithPrefix(prefix string) *AdminAccessCasesTable {
	return newAdminAccessCasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AdminAccessCasesTable with assigned table suffix
func (a AdminAccessCasesTable) WithSuffix(suffix string) *AdminAccessCasesTable {
	return newAdminAccessCasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAdminAccessCasesTable(schemaName, tableName, alias string) *AdminAccessCasesTable {
	return &AdminAccessCasesTable{
		adminAccessCasesTable: newAdminAccessCasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newAdminAccessCasesTableImpl("", "excluded", ""),
	}
}

func newAdminAccessCasesTableImpl(schemaName, tableName, alias string) adminAccessCasesTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		ActorIDColumn      = postgres.StringColumn("actor_id")
		TargetUserIDColumn = postgres.StringColumn("target_user_id")
		ReasonColumn       = postgres.StringColumn("reason")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		ExpiresAtColumn    = postgres.TimestampzColumn("expires_at")
		allColumns         = postgres.ColumnList{IDColumn, ActorIDColumn, TargetUserIDColumn, ReasonColumn, CreatedAtColumn, ExpiresAtColumn}
		mutableColumns     = postgres.ColumnList{ActorIDColumn, TargetUserIDColumn, ReasonColumn, CreatedAtColumn, ExpiresAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn, ExpiresAtColumn}
	)

	return adminAccessCasesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ActorID:      ActorIDColumn,
		TargetUserID: TargetUserIDColumn,
		Reason:       ReasonColumn,
		CreatedAt:    CreatedAtColumn,
		ExpiresAt:    ExpiresAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
