//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CryptoAccounts = newCryptoAccountsTable("public", "crypto_accounts", "")

type cryptoAccountsTable struct {
	postgres.Table

	// Columns
	UserID              postgres.ColumnString
	EncryptionPublicKey postgres.ColumnString
	SigningPublicKey    postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CryptoAccountsTable struct {
	cryptoAccountsTable

	EXCLUDED cryptoAccountsTable
}

// AS creates new CryptoAccountsTable with assigned alias
func (a CryptoAccountsTable) AS(alias string) *CryptoAccountsTable {
	return newCryptoAccountsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CryptoAccountsTable with assigned schema name
func (a CryptoAccountsTable) FromSchema(schemaName string) *CryptoAccountsTable {
	return newCryptoAccountsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CryptoAccountsTable with assigned table prefix
func (a CryptoAccountsTable) WithPrefix(prefix string) *CryptoAccountsTable {
	return newCryptoAccountsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CryptoAccountsTable with assigned table suffix
func (a CryptoAccountsTable) WithSuffix(suffix string) *CryptoAccountsTable {
	return newCryptoAccountsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCryptoAccountsTable(schemaName, tableName, alias string) *CryptoAccountsTable {
	return &CryptoAccountsTable{
		cryptoAccountsTable: newCryptoAccountsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCryptoAccountsTableImpl("", "excluded", ""),
	}
}

func newCryptoAccountsTableImpl(schemaName, tableName, alias string) cryptoAccountsTable {
	var (
		UserIDColumn              = postgres.StringColumn("user_id")
		EncryptionPublicKeyColumn = postgres.StringColumn("encryption_public_key")
		SigningPublicKeyColumn    = postgres.StringColumn("signing_public_key")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{UserIDColumn, EncryptionPublicKeyColumn, SigningPublicKeyColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{EncryptionPublicKeyColumn, SigningPublicKeyColumn, CreatedAtColumn}
		defaultColumns            = postgres.ColumnList{CreatedAtColumn}
	)

	return cryptoAccountsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:              UserIDColumn,
		EncryptionPublicKey: EncryptionPublicKeyColumn,
		SigningPublicKey:    SigningPublicKeyColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
