//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CryptoDevices = newCryptoDevicesTable("public", "crypto_devices", "")

type cryptoDevicesTable struct {
	postgres.Table

	// Columns
	UserID      postgres.ColumnString
	ID          postgres.ColumnString
	PublicKey   postgres.ColumnString
	WrappedKeys postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CryptoDevicesTable struct {
	cryptoDevicesTable

	EXCLUDED cryptoDevicesTable
}

// AS creates new CryptoDevicesTable with assigned alias
func (a CryptoDevicesTable) AS(alias string) *CryptoDevicesTable {
	return newCryptoDevicesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CryptoDevicesTable with assigned schema name
func (a CryptoDevicesTable) FromSchema(schemaName string) *CryptoDevicesTable {
	return newCryptoDevicesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CryptoDevicesTable with assigned table prefix
func (a CryptoDevicesTable) WithPrefix(prefix string) *CryptoDevicesTable {
	return newCryptoDevicesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CryptoDevicesTable with assigned table suffix
func (a CryptoDevicesTable) WithSuffix(suffix string) *CryptoDevicesTable {
	return newCryptoDevicesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCryptoDevicesTable(schemaName, tableName, alias string) *CryptoDevicesTable {
	return &CryptoDevicesTable{
		cryptoDevicesTable: newCryptoDevicesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newCryptoDevicesTableImpl("", "excluded", ""),
	}
}

func newCryptoDevicesTableImpl(schemaName, tableName, alias string) cryptoDevicesTable {
	var (
		UserIDColumn      = postgres.StringColumn("user_id")
		IDColumn          = postgres.StringColumn("id")
		PublicKeyColumn   = postgres.StringColumn("public_key")
		WrappedKeysColumn = postgres.StringColumn("wrapped_keys")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{UserIDColumn, IDColumn, PublicKeyColumn, WrappedKeysColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{PublicKeyColumn, WrappedKeysColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{WrappedKeysColumn, CreatedAtColumn}
	)

	return cryptoDevicesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:      UserIDColumn,
		ID:          IDColumn,
		PublicKey:   PublicKeyColumn,
		WrappedKeys: WrappedKeysColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
