//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CryptoRecovery = newCryptoRecoveryTable("public", "crypto_recovery", "")

type cryptoRecoveryTable struct {
	postgres.Table

	// Columns
	UserID      postgres.ColumnString
	WrappedKeys postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CryptoRecoveryTable struct {
	cryptoRecoveryTable

	EXCLUDED cryptoRecoveryTable
}

// AS creates new CryptoRecoveryTable with assigned alias
func (a CryptoRecoveryTable) AS(alias string) *CryptoRecoveryTable {
	return newCryptoRecoveryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CryptoRecoveryTable with assigned schema name
func (a CryptoRecoveryTable) FromSchema(schemaName string) *CryptoRecoveryTable {
	return newCryptoRecoveryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CryptoRecoveryTable with assigned table prefix
func (a CryptoRecoveryTable) WithPrefix(prefix string) *CryptoRecoveryTable {
	return newCryptoRecoveryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CryptoRecoveryTable with assigned table suffix
func (a CryptoRecoveryTable) WithSuffix(suffix string) *CryptoRecoveryTable {
	return newCryptoRecoveryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCryptoRecoveryTable(schemaName, tableName, alias string) *CryptoRecoveryTable {
	return &CryptoRecoveryTable{
		cryptoRecoveryTable: newCryptoRecoveryTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCryptoRecoveryTableImpl("", "excluded", ""),
	}
}

func newCryptoRecoveryTableImpl(schemaName, tableName, alias string) cryptoRecoveryTable {
	var (
		UserIDColumn      = postgres.StringColumn("user_id")
		WrappedKeysColumn = postgres.StringColumn("wrapped_keys")
		allColumns        = postgres.ColumnList{UserIDColumn, WrappedKeysColumn}
		mutableColumns    = postgres.ColumnList{WrappedKeysColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return cryptoRecoveryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:      UserIDColumn,
		WrappedKeys: WrappedKeysColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
