//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoKeyringGrants = newFluoKeyringGrantsTable("public", "fluo_keyring_grants", "")

type fluoKeyringGrantsTable struct {
	postgres.Table

	// Columns
	OwnerID     postgres.ColumnString
	Version     postgres.ColumnInteger
	RecipientID postgres.ColumnString
	SealedKey   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoKeyringGrantsTable struct {
	fluoKeyringGrantsTable

	EXCLUDED fluoKeyringGrantsTable
}

// AS creates new FluoKeyringGrantsTable with assigned alias
func (a FluoKeyringGrantsTable) AS(alias string) *FluoKeyringGrantsTable {
	return newFluoKeyringGrantsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoKeyringGrantsTable with assigned schema name
func (a FluoKeyringGrantsTable) FromSchema(schemaName string) *FluoKeyringGrantsTable {
	return newFluoKeyringGrantsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoKeyringGrantsTable with assigned table prefix
func (a FluoKeyringGrantsTable) WithPrefix(prefix string) *FluoKeyringGrantsTable {
	return newFluoKeyringGrantsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoKeyringGrantsTable with assigned table suffix
func (a FluoKeyringGrantsTable) WithSuffix(suffix string) *FluoKeyringGrantsTable {
	return newFluoKeyringGrantsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoKeyringGrantsTable(schemaName, tableName, alias string) *FluoKeyringGrantsTable {
	return &FluoKeyringGrantsTable{
		fluoKeyringGrantsTable: newFluoKeyringGrantsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newFluoKeyringGrantsTableImpl("", "excluded", ""),
	}
}

func newFluoKeyringGrantsTableImpl(schemaName, tableName, alias string) fluoKeyringGrantsTable {
	var (
		OwnerIDColumn     = postgres.StringColumn("owner_id")
		VersionColumn     = postgres.IntegerColumn("version")
		RecipientIDColumn = postgres.StringColumn("recipient_id")
		SealedKeyColumn   = postgres.StringColumn("sealed_key")
		allColumns        = postgres.ColumnList{OwnerIDColumn, VersionColumn, RecipientIDColumn, SealedKeyColumn}
		mutableColumns    = postgres.ColumnList{SealedKeyColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return fluoKeyringGrantsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OwnerID:     OwnerIDColumn,
		Version:     VersionColumn,
		RecipientID: RecipientIDColumn,
		SealedKey:   SealedKeyColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
