//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoSettings = newFluoSettingsTable("public", "fluo_settings", "")

type fluoSettingsTable struct {
	postgres.Table

	// Columns
	UserID            postgres.ColumnString
	NotifyLikes       postgres.ColumnString
	NotifyDislikes    postgres.ColumnString
	NotifyReplies     postgres.ColumnString
	NotifyFollows     postgres.ColumnString
	NotifyUnfollows   postgres.ColumnString
	NotifyQuotes      postgres.ColumnString
	AccountVisibility postgres.ColumnString
	ShowLikes         postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoSettingsTable struct {
	fluoSettingsTable

	EXCLUDED fluoSettingsTable
}

// AS creates new FluoSettingsTable with assigned alias
func (a FluoSettingsTable) AS(alias string) *FluoSettingsTable {
	return newFluoSettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoSettingsTable with assigned schema name
func (a FluoSettingsTable) FromSchema(schemaName string) *FluoSettingsTable {
	return newFluoSettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoSettingsTable with assigned table prefix
func (a FluoSettingsTable) WithPrefix(prefix string) *FluoSettingsTable {
	return newFluoSettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoSettingsTable with assigned table suffix
func (a FluoSettingsTable) WithSuffix(suffix string) *FluoSettingsTable {
	return newFluoSettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoSettingsTable(schemaName, tableName, alias string) *FluoSettingsTable {
	return &FluoSettingsTable{
		fluoSettingsTable: newFluoSettingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newFluoSettingsTableImpl("", "excluded", ""),
	}
}

func newFluoSettingsTableImpl(schemaName, tableName, alias string) fluoSettingsTable {
	var (
		UserIDColumn            = postgres.StringColumn("user_id")
		NotifyLikesColumn       = postgres.StringColumn("notify_likes")
		NotifyDislikesColumn    = postgres.StringColumn("notify_dislikes")
		NotifyRepliesColumn     = postgres.StringColumn("notify_replies")
		NotifyFollowsColumn     = postgres.StringColumn("notify_follows")
		NotifyUnfollowsColumn   = postgres.StringColumn("notify_unfollows")
		NotifyQuotesColumn      = postgres.StringColumn("notify_quotes")
		AccountVisibilityColumn = postgres.StringColumn("account_visibility")
		ShowLikesColumn         = postgres.BoolColumn("show_likes")
		allColumns              = postgres.ColumnList{UserIDColumn, NotifyLikesColumn, NotifyDislikesColumn, NotifyRepliesColumn, NotifyFollowsColumn, NotifyUnfollowsColumn, NotifyQuotesColumn, AccountVisibilityColumn, ShowLikesColumn}
		mutableColumns          = postgres.ColumnList{NotifyLikesColumn, NotifyDislikesColumn, NotifyRepliesColumn, NotifyFollowsColumn, NotifyUnfollowsColumn, NotifyQuotesColumn, AccountVisibilityColumn, ShowLikesColumn}
		defaultColumns          = postgres.ColumnList{NotifyLikesColumn, NotifyDislikesColumn, NotifyRepliesColumn, NotifyFollowsColumn, NotifyUnfollowsColumn, NotifyQuotesColumn, AccountVisibilityColumn, ShowLikesColumn}
	)

	return fluoSettingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:            UserIDColumn,
		NotifyLikes:       NotifyLikesColumn,
		NotifyDislikes:    NotifyDislikesColumn,
		NotifyReplies:     NotifyRepliesColumn,
		NotifyFollows:     NotifyFollowsColumn,
		NotifyUnfollows:   NotifyUnfollowsColumn,
		NotifyQuotes:      NotifyQuotesColumn,
		AccountVisibility: AccountVisibilityColumn,
		ShowLikes:         ShowLikesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
