//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoFollows = newFluoFollowsTable("public", "fluo_follows", "")

type fluoFollowsTable struct {
	postgres.Table

	// Columns
	FollowerID postgres.ColumnString
	FollowedID postgres.ColumnString
	CreatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoFollowsTable struct {
	fluoFollowsTable

	EXCLUDED fluoFollowsTable
}

// AS creates new FluoFollowsTable with assigned alias
func (a FluoFollowsTable) AS(alias string) *FluoFollowsTable {
	return newFluoFollowsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoFollowsTable with assigned schema name
func (a FluoFollowsTable) FromSchema(schemaName string) *FluoFollowsTable {
	return newFluoFollowsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoFollowsTable with assigned table prefix
func (a FluoFollowsTable) WithPrefix(prefix string) *FluoFollowsTable {
	return newFluoFollowsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoFollowsTable with assigned table suffix
func (a FluoFollowsTable) WithSuffix(suffix string) *FluoFollowsTable {
	return newFluoFollowsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoFollowsTable(schemaName, tableName, alias string) *FluoFollowsTable {
	return &FluoFollowsTable{
		fluoFollowsTable: newFluoFollowsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newFluoFollowsTableImpl("", "excluded", ""),
	}
}

func newFluoFollowsTableImpl(schemaName, tableName, alias string) fluoFollowsTable {
	var (
		FollowerIDColumn = postgres.StringColumn("follower_id")
		FollowedIDColumn = postgres.StringColumn("followed_id")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		allColumns       = postgres.ColumnList{FollowerIDColumn, FollowedIDColumn, CreatedAtColumn}
		mutableColumns   = postgres.ColumnList{CreatedAtColumn}
		defaultColumns   = postgres.ColumnList{CreatedAtColumn}
	)

	return fluoFollowsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		FollowerID: FollowerIDColumn,
		FollowedID: FollowedIDColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
