//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoPosts = newFluoPostsTable("public", "fluo_posts", "")

type fluoPostsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	AuthorID     postgres.ColumnString
	Content      postgres.ColumnString
	PlainText    postgres.ColumnString
	Visibility   postgres.ColumnString
	ParentID     postgres.ColumnString
	QuoteID      postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	QuoteDeleted postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoPostsTable struct {
	fluoPostsTable

	EXCLUDED fluoPostsTable
}

// AS creates new FluoPostsTable with assigned alias
func (a FluoPostsTable) AS(alias string) *FluoPostsTable {
	return newFluoPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoPostsTable with assigned schema name
func (a FluoPostsTable) FromSchema(schemaName string) *FluoPostsTable {
	return newFluoPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoPostsTable with assigned table prefix
func (a FluoPostsTable) WithPrefix(prefix string) *FluoPostsTable {
	return newFluoPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoPostsTable with assigned table suffix
func (a FluoPostsTable) WithSuffix(suffix string) *FluoPostsTable {
	return newFluoPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoPostsTable(schemaName, tableName, alias string) *FluoPostsTable {
	return &FluoPostsTable{
		fluoPostsTable: newFluoPostsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newFluoPostsTableImpl("", "excluded", ""),
	}
}

func newFluoPostsTableImpl(schemaName, tableName, alias string) fluoPostsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		AuthorIDColumn     = postgres.StringColumn("author_id")
		ContentColumn      = postgres.StringColumn("content")
		PlainTextColumn    = postgres.StringColumn("plain_text")
		VisibilityColumn   = postgres.StringColumn("visibility")
		ParentIDColumn     = postgres.StringColumn("parent_id")
		QuoteIDColumn      = postgres.StringColumn("quote_id")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		QuoteDeletedColumn = postgres.BoolColumn("quote_deleted")
		allColumns         = postgres.ColumnList{IDColumn, AuthorIDColumn, ContentColumn, PlainTextColumn, VisibilityColumn, ParentIDColumn, QuoteIDColumn, CreatedAtColumn, UpdatedAtColumn, QuoteDeletedColumn}
		mutableColumns     = postgres.ColumnList{AuthorIDColumn, ContentColumn, PlainTextColumn, VisibilityColumn, ParentIDColumn, QuoteIDColumn, CreatedAtColumn, UpdatedAtColumn, QuoteDeletedColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, QuoteDeletedColumn}
	)

	return fluoPostsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		AuthorID:     AuthorIDColumn,
		Content:      ContentColumn,
		PlainText:    PlainTextColumn,
		Visibility:   VisibilityColumn,
		ParentID:     ParentIDColumn,
		QuoteID:      QuoteIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		QuoteDeleted: QuoteDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
