//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoProfiles = newFluoProfilesTable("public", "fluo_profiles", "")

type fluoProfilesTable struct {
	postgres.Table

	// Columns
	UserID       postgres.ColumnString
	Nickname     postgres.ColumnString
	Bio          postgres.ColumnString
	BirthDate    postgres.ColumnDate
	Location     postgres.ColumnString
	Website      postgres.ColumnString
	Pronouns     postgres.ColumnString
	Verified     postgres.ColumnBool
	Status       postgres.ColumnString
	LastActiveAt postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoProfilesTable struct {
	fluoProfilesTable

	EXCLUDED fluoProfilesTable
}

// AS creates new FluoProfilesTable with assigned alias
func (a FluoProfilesTable) AS(alias string) *FluoProfilesTable {
	return newFluoProfilesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoProfilesTable with assigned schema name
func (a FluoProfilesTable) FromSchema(schemaName string) *FluoProfilesTable {
	return newFluoProfilesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoProfilesTable with assigned table prefix
func (a FluoProfilesTable) WithPrefix(prefix string) *FluoProfilesTable {
	return newFluoProfilesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoProfilesTable with assigned table suffix
func (a FluoProfilesTable) WithSuffix(suffix string) *FluoProfilesTable {
	return newFluoProfilesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoProfilesTable(schemaName, tableName, alias string) *FluoProfilesTable {
	return &FluoProfilesTable{
		fluoProfilesTable: newFluoProfilesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newFluoProfilesTableImpl("", "excluded", ""),
	}
}

func newFluoProfilesTableImpl(schemaName, tableName, alias string) fluoProfilesTable {
	var (
		UserIDColumn       = postgres.StringColumn("user_id")
		NicknameColumn     = postgres.StringColumn("nickname")
		BioColumn          = postgres.StringColumn("bio")
		BirthDateColumn    = postgres.DateColumn("birth_date")
		LocationColumn     = postgres.StringColumn("location")
		WebsiteColumn      = postgres.StringColumn("website")
		PronounsColumn     = postgres.StringColumn("pronouns")
		VerifiedColumn     = postgres.BoolColumn("verified")
		StatusColumn       = postgres.StringColumn("status")
		LastActiveAtColumn = postgres.TimestampzColumn("last_active_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		allColumns         = postgres.ColumnList{UserIDColumn, NicknameColumn, BioColumn, BirthDateColumn, LocationColumn, WebsiteColumn, PronounsColumn, VerifiedColumn, StatusColumn, LastActiveAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{NicknameColumn, BioColumn, BirthDateColumn, LocationColumn, WebsiteColumn, PronounsColumn, VerifiedColumn, StatusColumn, LastActiveAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{NicknameColumn, BioColumn, LocationColumn, WebsiteColumn, PronounsColumn, VerifiedColumn, StatusColumn, UpdatedAtColumn}
	)

	return fluoProfilesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:       UserIDColumn,
		Nickname:     NicknameColumn,
		Bio:          BioColumn,
		BirthDate:    BirthDateColumn,
		Location:     LocationColumn,
		Website:      WebsiteColumn,
		Pronouns:     PronounsColumn,
		Verified:     VerifiedColumn,
		Status:       StatusColumn,
		LastActiveAt: LastActiveAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
