//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoKeyrings = newFluoKeyringsTable("public", "fluo_keyrings", "")

type fluoKeyringsTable struct {
	postgres.Table

	// Columns
	OwnerID   postgres.ColumnString
	Version   postgres.ColumnInteger
	PublicKey postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoKeyringsTable struct {
	fluoKeyringsTable

	EXCLUDED fluoKeyringsTable
}

// AS creates new FluoKeyringsTable with assigned alias
func (a FluoKeyringsTable) AS(alias string) *FluoKeyringsTable {
	return newFluoKeyringsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoKeyringsTable with assigned schema name
func (a FluoKeyringsTable) FromSchema(schemaName string) *FluoKeyringsTable {
	return newFluoKeyringsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoKeyringsTable with assigned table prefix
func (a FluoKeyringsTable) WithPrefix(prefix string) *FluoKeyringsTable {
	return newFluoKeyringsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoKeyringsTable with assigned table suffix
func (a FluoKeyringsTable) WithSuffix(suffix string) *FluoKeyringsTable {
	return newFluoKeyringsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoKeyringsTable(schemaName, tableName, alias string) *FluoKeyringsTable {
	return &FluoKeyringsTable{
		fluoKeyringsTable: newFluoKeyringsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newFluoKeyringsTableImpl("", "excluded", ""),
	}
}

func newFluoKeyringsTableImpl(schemaName, tableName, alias string) fluoKeyringsTable {
	var (
		OwnerIDColumn   = postgres.StringColumn("owner_id")
		VersionColumn   = postgres.IntegerColumn("version")
		PublicKeyColumn = postgres.StringColumn("public_key")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{OwnerIDColumn, VersionColumn, PublicKeyColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{PublicKeyColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return fluoKeyringsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OwnerID:   OwnerIDColumn,
		Version:   VersionColumn,
		PublicKey: PublicKeyColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
