//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoProfileImages = newFluoProfileImagesTable("public", "fluo_profile_images", "")

type fluoProfileImagesTable struct {
	postgres.Table

	// Columns
	UserID    postgres.ColumnString
	Slot      postgres.ColumnString
	UploadID  postgres.ColumnString
	MimeType  postgres.ColumnString
	Width     postgres.ColumnInteger
	Height    postgres.ColumnInteger
	SizeBytes postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoProfileImagesTable struct {
	fluoProfileImagesTable

	EXCLUDED fluoProfileImagesTable
}

// AS creates new FluoProfileImagesTable with assigned alias
func (a FluoProfileImagesTable) AS(alias string) *FluoProfileImagesTable {
	return newFluoProfileImagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoProfileImagesTable with assigned schema name
func (a FluoProfileImagesTable) FromSchema(schemaName string) *FluoProfileImagesTable {
	return newFluoProfileImagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoProfileImagesTable with assigned table prefix
func (a FluoProfileImagesTable) WithPrefix(prefix string) *FluoProfileImagesTable {
	return newFluoProfileImagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoProfileImagesTable with assigned table suffix
func (a FluoProfileImagesTable) WithSuffix(suffix string) *FluoProfileImagesTable {
	return newFluoProfileImagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoProfileImagesTable(schemaName, tableName, alias string) *FluoProfileImagesTable {
	return &FluoProfileImagesTable{
		fluoProfileImagesTable: newFluoProfileImagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newFluoProfileImagesTableImpl("", "excluded", ""),
	}
}

func newFluoProfileImagesTableImpl(schemaName, tableName, alias string) fluoProfileImagesTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		SlotColumn      = postgres.StringColumn("slot")
		UploadIDColumn  = postgres.StringColumn("upload_id")
		MimeTypeColumn  = postgres.StringColumn("mime_type")
		WidthColumn     = postgres.IntegerColumn("width")
		HeightColumn    = postgres.IntegerColumn("height")
		SizeBytesColumn = postgres.IntegerColumn("size_bytes")
		allColumns      = postgres.ColumnList{UserIDColumn, SlotColumn, UploadIDColumn, MimeTypeColumn, WidthColumn, HeightColumn, SizeBytesColumn}
		mutableColumns  = postgres.ColumnList{UploadIDColumn, MimeTypeColumn, WidthColumn, HeightColumn, SizeBytesColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return fluoProfileImagesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		Slot:      SlotColumn,
		UploadID:  UploadIDColumn,
		MimeType:  MimeTypeColumn,
		Width:     WidthColumn,
		Height:    HeightColumn,
		SizeBytes: SizeBytesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
