//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoReactions = newFluoReactionsTable("public", "fluo_reactions", "")

type fluoReactionsTable struct {
	postgres.Table

	// Columns
	PostID    postgres.ColumnString
	UserID    postgres.ColumnString
	Value     postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoReactionsTable struct {
	fluoReactionsTable

	EXCLUDED fluoReactionsTable
}

// AS creates new FluoReactionsTable with assigned alias
func (a FluoReactionsTable) AS(alias string) *FluoReactionsTable {
	return newFluoReactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoReactionsTable with assigned schema name
func (a FluoReactionsTable) FromSchema(schemaName string) *FluoReactionsTable {
	return newFluoReactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoReactionsTable with assigned table prefix
func (a FluoReactionsTable) WithPrefix(prefix string) *FluoReactionsTable {
	return newFluoReactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoReactionsTable with assigned table suffix
func (a FluoReactionsTable) WithSuffix(suffix string) *FluoReactionsTable {
	return newFluoReactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoReactionsTable(schemaName, tableName, alias string) *FluoReactionsTable {
	return &FluoReactionsTable{
		fluoReactionsTable: newFluoReactionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newFluoReactionsTableImpl("", "excluded", ""),
	}
}

func newFluoReactionsTableImpl(schemaName, tableName, alias string) fluoReactionsTable {
	var (
		PostIDColumn    = postgres.StringColumn("post_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		ValueColumn     = postgres.StringColumn("value")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{PostIDColumn, UserIDColumn, ValueColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{ValueColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return fluoReactionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostID:    PostIDColumn,
		UserID:    UserIDColumn,
		Value:     ValueColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
