//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoNotifications = newFluoNotificationsTable("public", "fluo_notifications", "")

type fluoNotificationsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	RecipientID   postgres.ColumnString
	ActorID       postgres.ColumnString
	Kind          postgres.ColumnString
	PostID        postgres.ColumnString
	SubjectPostID postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	ReadAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoNotificationsTable struct {
	fluoNotificationsTable

	EXCLUDED fluoNotificationsTable
}

// AS creates new FluoNotificationsTable with assigned alias
func (a FluoNotificationsTable) AS(alias string) *FluoNotificationsTable {
	return newFluoNotificationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoNotificationsTable with assigned schema name
func (a FluoNotificationsTable) FromSchema(schemaName string) *FluoNotificationsTable {
	return newFluoNotificationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoNotificationsTable with assigned table prefix
func (a FluoNotificationsTable) WithPrefix(prefix string) *FluoNotificationsTable {
	return newFluoNotificationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoNotificationsTable with assigned table suffix
func (a FluoNotificationsTable) WithSuffix(suffix string) *FluoNotificationsTable {
	return newFluoNotificationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoNotificationsTable(schemaName, tableName, alias string) *FluoNotificationsTable {
	return &FluoNotificationsTable{
		fluoNotificationsTable: newFluoNotificationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newFluoNotificationsTableImpl("", "excluded", ""),
	}
}

func newFluoNotificationsTableImpl(schemaName, tableName, alias string) fluoNotificationsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		RecipientIDColumn   = postgres.StringColumn("recipient_id")
		ActorIDColumn       = postgres.StringColumn("actor_id")
		KindColumn          = postgres.StringColumn("kind")
		PostIDColumn        = postgres.StringColumn("post_id")
		SubjectPostIDColumn = postgres.StringColumn("subject_post_id")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		ReadAtColumn        = postgres.TimestampzColumn("read_at")
		allColumns          = postgres.ColumnList{IDColumn, RecipientIDColumn, ActorIDColumn, KindColumn, PostIDColumn, SubjectPostIDColumn, CreatedAtColumn, ReadAtColumn}
		mutableColumns      = postgres.ColumnList{RecipientIDColumn, ActorIDColumn, KindColumn, PostIDColumn, SubjectPostIDColumn, CreatedAtColumn, ReadAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return fluoNotificationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		RecipientID:   RecipientIDColumn,
		ActorID:       ActorIDColumn,
		Kind:          KindColumn,
		PostID:        PostIDColumn,
		SubjectPostID: SubjectPostIDColumn,
		CreatedAt:     CreatedAtColumn,
		ReadAt:        ReadAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
