//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoSavedPosts = newFluoSavedPostsTable("public", "fluo_saved_posts", "")

type fluoSavedPostsTable struct {
	postgres.Table

	// Columns
	UserID  postgres.ColumnString
	PostID  postgres.ColumnString
	SavedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoSavedPostsTable struct {
	fluoSavedPostsTable

	EXCLUDED fluoSavedPostsTable
}

// AS creates new FluoSavedPostsTable with assigned alias
func (a FluoSavedPostsTable) AS(alias string) *FluoSavedPostsTable {
	return newFluoSavedPostsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoSavedPostsTable with assigned schema name
func (a FluoSavedPostsTable) FromSchema(schemaName string) *FluoSavedPostsTable {
	return newFluoSavedPostsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoSavedPostsTable with assigned table prefix
func (a FluoSavedPostsTable) WithPrefix(prefix string) *FluoSavedPostsTable {
	return newFluoSavedPostsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoSavedPostsTable with assigned table suffix
func (a FluoSavedPostsTable) WithSuffix(suffix string) *FluoSavedPostsTable {
	return newFluoSavedPostsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoSavedPostsTable(schemaName, tableName, alias string) *FluoSavedPostsTable {
	return &FluoSavedPostsTable{
		fluoSavedPostsTable: newFluoSavedPostsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newFluoSavedPostsTableImpl("", "excluded", ""),
	}
}

func newFluoSavedPostsTableImpl(schemaName, tableName, alias string) fluoSavedPostsTable {
	var (
		UserIDColumn   = postgres.StringColumn("user_id")
		PostIDColumn   = postgres.StringColumn("post_id")
		SavedAtColumn  = postgres.TimestampzColumn("saved_at")
		allColumns     = postgres.ColumnList{UserIDColumn, PostIDColumn, SavedAtColumn}
		mutableColumns = postgres.ColumnList{SavedAtColumn}
		defaultColumns = postgres.ColumnList{SavedAtColumn}
	)

	return fluoSavedPostsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:  UserIDColumn,
		PostID:  PostIDColumn,
		SavedAt: SavedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
