//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FluoPostMedia = newFluoPostMediaTable("public", "fluo_post_media", "")

type fluoPostMediaTable struct {
	postgres.Table

	// Columns
	PostID    postgres.ColumnString
	UploadID  postgres.ColumnString
	Position  postgres.ColumnInteger
	Kind      postgres.ColumnString
	MimeType  postgres.ColumnString
	Width     postgres.ColumnInteger
	Height    postgres.ColumnInteger
	SizeBytes postgres.ColumnInteger
	AltText   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FluoPostMediaTable struct {
	fluoPostMediaTable

	EXCLUDED fluoPostMediaTable
}

// AS creates new FluoPostMediaTable with assigned alias
func (a FluoPostMediaTable) AS(alias string) *FluoPostMediaTable {
	return newFluoPostMediaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FluoPostMediaTable with assigned schema name
func (a FluoPostMediaTable) FromSchema(schemaName string) *FluoPostMediaTable {
	return newFluoPostMediaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FluoPostMediaTable with assigned table prefix
func (a FluoPostMediaTable) WithPrefix(prefix string) *FluoPostMediaTable {
	return newFluoPostMediaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FluoPostMediaTable with assigned table suffix
func (a FluoPostMediaTable) WithSuffix(suffix string) *FluoPostMediaTable {
	return newFluoPostMediaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFluoPostMediaTable(schemaName, tableName, alias string) *FluoPostMediaTable {
	return &FluoPostMediaTable{
		fluoPostMediaTable: newFluoPostMediaTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newFluoPostMediaTableImpl("", "excluded", ""),
	}
}

func newFluoPostMediaTableImpl(schemaName, tableName, alias string) fluoPostMediaTable {
	var (
		PostIDColumn    = postgres.StringColumn("post_id")
		UploadIDColumn  = postgres.StringColumn("upload_id")
		PositionColumn  = postgres.IntegerColumn("position")
		KindColumn      = postgres.StringColumn("kind")
		MimeTypeColumn  = postgres.StringColumn("mime_type")
		WidthColumn     = postgres.IntegerColumn("width")
		HeightColumn    = postgres.IntegerColumn("height")
		SizeBytesColumn = postgres.IntegerColumn("size_bytes")
		AltTextColumn   = postgres.StringColumn("alt_text")
		allColumns      = postgres.ColumnList{PostIDColumn, UploadIDColumn, PositionColumn, KindColumn, MimeTypeColumn, WidthColumn, HeightColumn, SizeBytesColumn, AltTextColumn}
		mutableColumns  = postgres.ColumnList{PositionColumn, KindColumn, MimeTypeColumn, WidthColumn, HeightColumn, SizeBytesColumn, AltTextColumn}
		defaultColumns  = postgres.ColumnList{AltTextColumn}
	)

	return fluoPostMediaTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostID:    PostIDColumn,
		UploadID:  UploadIDColumn,
		Position:  PositionColumn,
		Kind:      KindColumn,
		MimeType:  MimeTypeColumn,
		Width:     WidthColumn,
		Height:    HeightColumn,
		SizeBytes: SizeBytesColumn,
		AltText:   AltTextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
