//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LigoMessageMedia = newLigoMessageMediaTable("public", "ligo_message_media", "")

type ligoMessageMediaTable struct {
	postgres.Table

	// Columns
	MessageID postgres.ColumnString
	UploadID  postgres.ColumnString
	Position  postgres.ColumnInteger
	Kind      postgres.ColumnString
	MimeType  postgres.ColumnString
	Filename  postgres.ColumnString
	Width     postgres.ColumnInteger
	Height    postgres.ColumnInteger
	SizeBytes postgres.ColumnInteger
	AltText   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LigoMessageMediaTable struct {
	ligoMessageMediaTable

	EXCLUDED ligoMessageMediaTable
}

// AS creates new LigoMessageMediaTable with assigned alias
func (a LigoMessageMediaTable) AS(alias string) *LigoMessageMediaTable {
	return newLigoMessageMediaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LigoMessageMediaTable with assigned schema name
func (a LigoMessageMediaTable) FromSchema(schemaName string) *LigoMessageMediaTable {
	return newLigoMessageMediaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LigoMessageMediaTable with assigned table prefix
func (a LigoMessageMediaTable) WithPrefix(prefix string) *LigoMessageMediaTable {
	return newLigoMessageMediaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LigoMessageMediaTable with assigned table suffix
func (a LigoMessageMediaTable) WithSuffix(suffix string) *LigoMessageMediaTable {
	return newLigoMessageMediaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLigoMessageMediaTable(schemaName, tableName, alias string) *LigoMessageMediaTable {
	return &LigoMessageMediaTable{
		ligoMessageMediaTable: newLigoMessageMediaTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newLigoMessageMediaTableImpl("", "excluded", ""),
	}
}

func newLigoMessageMediaTableImpl(schemaName, tableName, alias string) ligoMessageMediaTable {
	var (
		MessageIDColumn = postgres.StringColumn("message_id")
		UploadIDColumn  = postgres.StringColumn("upload_id")
		PositionColumn  = postgres.IntegerColumn("position")
		KindColumn      = postgres.StringColumn("kind")
		MimeTypeColumn  = postgres.StringColumn("mime_type")
		FilenameColumn  = postgres.StringColumn("filename")
		WidthColumn     = postgres.IntegerColumn("width")
		HeightColumn    = postgres.IntegerColumn("height")
		SizeBytesColumn = postgres.IntegerColumn("size_bytes")
		AltTextColumn   = postgres.StringColumn("alt_text")
		allColumns      = postgres.ColumnList{MessageIDColumn, UploadIDColumn, PositionColumn, KindColumn, MimeTypeColumn, FilenameColumn, WidthColumn, HeightColumn, SizeBytesColumn, AltTextColumn}
		mutableColumns  = postgres.ColumnList{PositionColumn, KindColumn, MimeTypeColumn, FilenameColumn, WidthColumn, HeightColumn, SizeBytesColumn, AltTextColumn}
		defaultColumns  = postgres.ColumnList{FilenameColumn, AltTextColumn}
	)

	return ligoMessageMediaTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		MessageID: MessageIDColumn,
		UploadID:  UploadIDColumn,
		Position:  PositionColumn,
		Kind:      KindColumn,
		MimeType:  MimeTypeColumn,
		Filename:  FilenameColumn,
		Width:     WidthColumn,
		Height:    HeightColumn,
		SizeBytes: SizeBytesColumn,
		AltText:   AltTextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
