//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LigoConversations = newLigoConversationsTable("public", "ligo_conversations", "")

type ligoConversationsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Kind      postgres.ColumnString
	Title     postgres.ColumnString
	CreatedBy postgres.ColumnString
	DuoLow    postgres.ColumnString
	DuoHigh   postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LigoConversationsTable struct {
	ligoConversationsTable

	EXCLUDED ligoConversationsTable
}

// AS creates new LigoConversationsTable with assigned alias
func (a LigoConversationsTable) AS(alias string) *LigoConversationsTable {
	return newLigoConversationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LigoConversationsTable with assigned schema name
func (a LigoConversationsTable) FromSchema(schemaName string) *LigoConversationsTable {
	return newLigoConversationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LigoConversationsTable with assigned table prefix
func (a LigoConversationsTable) WithPrefix(prefix string) *LigoConversationsTable {
	return newLigoConversationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LigoConversationsTable with assigned table suffix
func (a LigoConversationsTable) WithSuffix(suffix string) *LigoConversationsTable {
	return newLigoConversationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLigoConversationsTable(schemaName, tableName, alias string) *LigoConversationsTable {
	return &LigoConversationsTable{
		ligoConversationsTable: newLigoConversationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newLigoConversationsTableImpl("", "excluded", ""),
	}
}

func newLigoConversationsTableImpl(schemaName, tableName, alias string) ligoConversationsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		KindColumn      = postgres.StringColumn("kind")
		TitleColumn     = postgres.StringColumn("title")
		CreatedByColumn = postgres.StringColumn("created_by")
		DuoLowColumn    = postgres.StringColumn("duo_low")
		DuoHighColumn   = postgres.StringColumn("duo_high")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, KindColumn, TitleColumn, CreatedByColumn, DuoLowColumn, DuoHighColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{KindColumn, TitleColumn, CreatedByColumn, DuoLowColumn, DuoHighColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, TitleColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return ligoConversationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Kind:      KindColumn,
		Title:     TitleColumn,
		CreatedBy: CreatedByColumn,
		DuoLow:    DuoLowColumn,
		DuoHigh:   DuoHighColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
