//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LigoMessageReactions = newLigoMessageReactionsTable("public", "ligo_message_reactions", "")

type ligoMessageReactionsTable struct {
	postgres.Table

	// Columns
	MessageID postgres.ColumnString
	UserID    postgres.ColumnString
	Emoji     postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LigoMessageReactionsTable struct {
	ligoMessageReactionsTable

	EXCLUDED ligoMessageReactionsTable
}

// AS creates new LigoMessageReactionsTable with assigned alias
func (a LigoMessageReactionsTable) AS(alias string) *LigoMessageReactionsTable {
	return newLigoMessageReactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LigoMessageReactionsTable with assigned schema name
func (a LigoMessageReactionsTable) FromSchema(schemaName string) *LigoMessageReactionsTable {
	return newLigoMessageReactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LigoMessageReactionsTable with assigned table prefix
func (a LigoMessageReactionsTable) WithPrefix(prefix string) *LigoMessageReactionsTable {
	return newLigoMessageReactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LigoMessageReactionsTable with assigned table suffix
func (a LigoMessageReactionsTable) WithSuffix(suffix string) *LigoMessageReactionsTable {
	return newLigoMessageReactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLigoMessageReactionsTable(schemaName, tableName, alias string) *LigoMessageReactionsTable {
	return &LigoMessageReactionsTable{
		ligoMessageReactionsTable: newLigoMessageReactionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newLigoMessageReactionsTableImpl("", "excluded", ""),
	}
}

func newLigoMessageReactionsTableImpl(schemaName, tableName, alias string) ligoMessageReactionsTable {
	var (
		MessageIDColumn = postgres.StringColumn("message_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		EmojiColumn     = postgres.StringColumn("emoji")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{MessageIDColumn, UserIDColumn, EmojiColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return ligoMessageReactionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		MessageID: MessageIDColumn,
		UserID:    UserIDColumn,
		Emoji:     EmojiColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
