//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LigoMembers = newLigoMembersTable("public", "ligo_members", "")

type ligoMembersTable struct {
	postgres.Table

	// Columns
	ConversationID         postgres.ColumnString
	UserID                 postgres.ColumnString
	JoinedAt               postgres.ColumnTimestampz
	LastReadMessageID      postgres.ColumnString
	LastDeliveredMessageID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LigoMembersTable struct {
	ligoMembersTable

	EXCLUDED ligoMembersTable
}

// AS creates new LigoMembersTable with assigned alias
func (a LigoMembersTable) AS(alias string) *LigoMembersTable {
	return newLigoMembersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LigoMembersTable with assigned schema name
func (a LigoMembersTable) FromSchema(schemaName string) *LigoMembersTable {
	return newLigoMembersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LigoMembersTable with assigned table prefix
func (a LigoMembersTable) WithPrefix(prefix string) *LigoMembersTable {
	return newLigoMembersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LigoMembersTable with assigned table suffix
func (a LigoMembersTable) WithSuffix(suffix string) *LigoMembersTable {
	return newLigoMembersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLigoMembersTable(schemaName, tableName, alias string) *LigoMembersTable {
	return &LigoMembersTable{
		ligoMembersTable: newLigoMembersTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newLigoMembersTableImpl("", "excluded", ""),
	}
}

func newLigoMembersTableImpl(schemaName, tableName, alias string) ligoMembersTable {
	var (
		ConversationIDColumn         = postgres.StringColumn("conversation_id")
		UserIDColumn                 = postgres.StringColumn("user_id")
		JoinedAtColumn               = postgres.TimestampzColumn("joined_at")
		LastReadMessageIDColumn      = postgres.StringColumn("last_read_message_id")
		LastDeliveredMessageIDColumn = postgres.StringColumn("last_delivered_message_id")
		allColumns                   = postgres.ColumnList{ConversationIDColumn, UserIDColumn, JoinedAtColumn, LastReadMessageIDColumn, LastDeliveredMessageIDColumn}
		mutableColumns               = postgres.ColumnList{JoinedAtColumn, LastReadMessageIDColumn, LastDeliveredMessageIDColumn}
		defaultColumns               = postgres.ColumnList{JoinedAtColumn}
	)

	return ligoMembersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ConversationID:         ConversationIDColumn,
		UserID:                 UserIDColumn,
		JoinedAt:               JoinedAtColumn,
		LastReadMessageID:      LastReadMessageIDColumn,
		LastDeliveredMessageID: LastDeliveredMessageIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
