//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LigoMessages = newLigoMessagesTable("public", "ligo_messages", "")

type ligoMessagesTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	ConversationID postgres.ColumnString
	SenderID       postgres.ColumnString
	ClientID       postgres.ColumnString
	Body           postgres.ColumnString
	CreatedAt      postgres.ColumnTimestampz
	EditedAt       postgres.ColumnTimestampz
	DeletedAt      postgres.ColumnTimestampz
	SystemNotice   postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LigoMessagesTable struct {
	ligoMessagesTable

	EXCLUDED ligoMessagesTable
}

// AS creates new LigoMessagesTable with assigned alias
func (a LigoMessagesTable) AS(alias string) *LigoMessagesTable {
	return newLigoMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LigoMessagesTable with assigned schema name
func (a LigoMessagesTable) FromSchema(schemaName string) *LigoMessagesTable {
	return newLigoMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LigoMessagesTable with assigned table prefix
func (a LigoMessagesTable) WithPrefix(prefix string) *LigoMessagesTable {
	return newLigoMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LigoMessagesTable with assigned table suffix
func (a LigoMessagesTable) WithSuffix(suffix string) *LigoMessagesTable {
	return newLigoMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLigoMessagesTable(schemaName, tableName, alias string) *LigoMessagesTable {
	return &LigoMessagesTable{
		ligoMessagesTable: newLigoMessagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newLigoMessagesTableImpl("", "excluded", ""),
	}
}

func newLigoMessagesTableImpl(schemaName, tableName, alias string) ligoMessagesTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		ConversationIDColumn = postgres.StringColumn("conversation_id")
		SenderIDColumn       = postgres.StringColumn("sender_id")
		ClientIDColumn       = postgres.StringColumn("client_id")
		BodyColumn           = postgres.StringColumn("body")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		EditedAtColumn       = postgres.TimestampzColumn("edited_at")
		DeletedAtColumn      = postgres.TimestampzColumn("deleted_at")
		SystemNoticeColumn   = postgres.BoolColumn("system_notice")
		allColumns           = postgres.ColumnList{IDColumn, ConversationIDColumn, SenderIDColumn, ClientIDColumn, BodyColumn, CreatedAtColumn, EditedAtColumn, DeletedAtColumn, SystemNoticeColumn}
		mutableColumns       = postgres.ColumnList{ConversationIDColumn, SenderIDColumn, ClientIDColumn, BodyColumn, CreatedAtColumn, EditedAtColumn, DeletedAtColumn, SystemNoticeColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, CreatedAtColumn, SystemNoticeColumn}
	)

	return ligoMessagesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ConversationID: ConversationIDColumn,
		SenderID:       SenderIDColumn,
		ClientID:       ClientIDColumn,
		Body:           BodyColumn,
		CreatedAt:      CreatedAtColumn,
		EditedAt:       EditedAtColumn,
		DeletedAt:      DeletedAtColumn,
		SystemNotice:   SystemNoticeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
