//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LingvoDictionaries = newLingvoDictionariesTable("public", "lingvo_dictionaries", "")

type lingvoDictionariesTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	UserID           postgres.ColumnString
	LearningLanguage postgres.ColumnString
	NativeLanguage   postgres.ColumnString
	DailyGoal        postgres.ColumnInteger
	TimeZone         postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LingvoDictionariesTable struct {
	lingvoDictionariesTable

	EXCLUDED lingvoDictionariesTable
}

// AS creates new LingvoDictionariesTable with assigned alias
func (a LingvoDictionariesTable) AS(alias string) *LingvoDictionariesTable {
	return newLingvoDictionariesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LingvoDictionariesTable with assigned schema name
func (a LingvoDictionariesTable) FromSchema(schemaName string) *LingvoDictionariesTable {
	return newLingvoDictionariesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LingvoDictionariesTable with assigned table prefix
func (a LingvoDictionariesTable) WithPrefix(prefix string) *LingvoDictionariesTable {
	return newLingvoDictionariesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LingvoDictionariesTable with assigned table suffix
func (a LingvoDictionariesTable) WithSuffix(suffix string) *LingvoDictionariesTable {
	return newLingvoDictionariesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLingvoDictionariesTable(schemaName, tableName, alias string) *LingvoDictionariesTable {
	return &LingvoDictionariesTable{
		lingvoDictionariesTable: newLingvoDictionariesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newLingvoDictionariesTableImpl("", "excluded", ""),
	}
}

func newLingvoDictionariesTableImpl(schemaName, tableName, alias string) lingvoDictionariesTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		UserIDColumn           = postgres.StringColumn("user_id")
		LearningLanguageColumn = postgres.StringColumn("learning_language")
		NativeLanguageColumn   = postgres.StringColumn("native_language")
		DailyGoalColumn        = postgres.IntegerColumn("daily_goal")
		TimeZoneColumn         = postgres.StringColumn("time_zone")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		allColumns             = postgres.ColumnList{IDColumn, UserIDColumn, LearningLanguageColumn, NativeLanguageColumn, DailyGoalColumn, TimeZoneColumn, CreatedAtColumn}
		mutableColumns         = postgres.ColumnList{UserIDColumn, LearningLanguageColumn, NativeLanguageColumn, DailyGoalColumn, TimeZoneColumn, CreatedAtColumn}
		defaultColumns         = postgres.ColumnList{IDColumn, DailyGoalColumn, TimeZoneColumn, CreatedAtColumn}
	)

	return lingvoDictionariesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		UserID:           UserIDColumn,
		LearningLanguage: LearningLanguageColumn,
		NativeLanguage:   NativeLanguageColumn,
		DailyGoal:        DailyGoalColumn,
		TimeZone:         TimeZoneColumn,
		CreatedAt:        CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
