//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LingvoReviews = newLingvoReviewsTable("public", "lingvo_reviews", "")

type lingvoReviewsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	DictionaryID      postgres.ColumnString
	CardID            postgres.ColumnString
	Rating            postgres.ColumnInteger
	Direction         postgres.ColumnString
	PreviousSchedule  postgres.ColumnString
	ResultingRevision postgres.ColumnInteger
	ReviewedAt        postgres.ColumnTimestampz
	UndoneAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LingvoReviewsTable struct {
	lingvoReviewsTable

	EXCLUDED lingvoReviewsTable
}

// AS creates new LingvoReviewsTable with assigned alias
func (a LingvoReviewsTable) AS(alias string) *LingvoReviewsTable {
	return newLingvoReviewsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LingvoReviewsTable with assigned schema name
func (a LingvoReviewsTable) FromSchema(schemaName string) *LingvoReviewsTable {
	return newLingvoReviewsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LingvoReviewsTable with assigned table prefix
func (a LingvoReviewsTable) WithPrefix(prefix string) *LingvoReviewsTable {
	return newLingvoReviewsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LingvoReviewsTable with assigned table suffix
func (a LingvoReviewsTable) WithSuffix(suffix string) *LingvoReviewsTable {
	return newLingvoReviewsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLingvoReviewsTable(schemaName, tableName, alias string) *LingvoReviewsTable {
	return &LingvoReviewsTable{
		lingvoReviewsTable: newLingvoReviewsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLingvoReviewsTableImpl("", "excluded", ""),
	}
}

func newLingvoReviewsTableImpl(schemaName, tableName, alias string) lingvoReviewsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		DictionaryIDColumn      = postgres.StringColumn("dictionary_id")
		CardIDColumn            = postgres.StringColumn("card_id")
		RatingColumn            = postgres.IntegerColumn("rating")
		DirectionColumn         = postgres.StringColumn("direction")
		PreviousScheduleColumn  = postgres.StringColumn("previous_schedule")
		ResultingRevisionColumn = postgres.IntegerColumn("resulting_revision")
		ReviewedAtColumn        = postgres.TimestampzColumn("reviewed_at")
		UndoneAtColumn          = postgres.TimestampzColumn("undone_at")
		allColumns              = postgres.ColumnList{IDColumn, DictionaryIDColumn, CardIDColumn, RatingColumn, DirectionColumn, PreviousScheduleColumn, ResultingRevisionColumn, ReviewedAtColumn, UndoneAtColumn}
		mutableColumns          = postgres.ColumnList{DictionaryIDColumn, CardIDColumn, RatingColumn, DirectionColumn, PreviousScheduleColumn, ResultingRevisionColumn, ReviewedAtColumn, UndoneAtColumn}
		defaultColumns          = postgres.ColumnList{ReviewedAtColumn}
	)

	return lingvoReviewsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		DictionaryID:      DictionaryIDColumn,
		CardID:            CardIDColumn,
		Rating:            RatingColumn,
		Direction:         DirectionColumn,
		PreviousSchedule:  PreviousScheduleColumn,
		ResultingRevision: ResultingRevisionColumn,
		ReviewedAt:        ReviewedAtColumn,
		UndoneAt:          UndoneAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
