//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LingvoCards = newLingvoCardsTable("public", "lingvo_cards", "")

type lingvoCardsTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	DictionaryID       postgres.ColumnString
	FolderID           postgres.ColumnString
	Kind               postgres.ColumnString
	Term               postgres.ColumnString
	Translation        postgres.ColumnString
	PartOfSpeech       postgres.ColumnString
	Article            postgres.ColumnString
	Plural             postgres.ColumnString
	Grammar            postgres.ColumnString
	Example            postgres.ColumnString
	ExampleTranslation postgres.ColumnString
	Notes              postgres.ColumnString
	SourceKey          postgres.ColumnString
	Status             postgres.ColumnString
	Schedule           postgres.ColumnString
	DueAt              postgres.ColumnTimestampz
	Revision           postgres.ColumnInteger
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LingvoCardsTable struct {
	lingvoCardsTable

	EXCLUDED lingvoCardsTable
}

// AS creates new LingvoCardsTable with assigned alias
func (a LingvoCardsTable) AS(alias string) *LingvoCardsTable {
	return newLingvoCardsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LingvoCardsTable with assigned schema name
func (a LingvoCardsTable) FromSchema(schemaName string) *LingvoCardsTable {
	return newLingvoCardsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LingvoCardsTable with assigned table prefix
func (a LingvoCardsTable) WithPrefix(prefix string) *LingvoCardsTable {
	return newLingvoCardsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LingvoCardsTable with assigned table suffix
func (a LingvoCardsTable) WithSuffix(suffix string) *LingvoCardsTable {
	return newLingvoCardsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLingvoCardsTable(schemaName, tableName, alias string) *LingvoCardsTable {
	return &LingvoCardsTable{
		lingvoCardsTable: newLingvoCardsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newLingvoCardsTableImpl("", "excluded", ""),
	}
}

func newLingvoCardsTableImpl(schemaName, tableName, alias string) lingvoCardsTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		DictionaryIDColumn       = postgres.StringColumn("dictionary_id")
		FolderIDColumn           = postgres.StringColumn("folder_id")
		KindColumn               = postgres.StringColumn("kind")
		TermColumn               = postgres.StringColumn("term")
		TranslationColumn        = postgres.StringColumn("translation")
		PartOfSpeechColumn       = postgres.StringColumn("part_of_speech")
		ArticleColumn            = postgres.StringColumn("article")
		PluralColumn             = postgres.StringColumn("plural")
		GrammarColumn            = postgres.StringColumn("grammar")
		ExampleColumn            = postgres.StringColumn("example")
		ExampleTranslationColumn = postgres.StringColumn("example_translation")
		NotesColumn              = postgres.StringColumn("notes")
		SourceKeyColumn          = postgres.StringColumn("source_key")
		StatusColumn             = postgres.StringColumn("status")
		ScheduleColumn           = postgres.StringColumn("schedule")
		DueAtColumn              = postgres.TimestampzColumn("due_at")
		RevisionColumn           = postgres.IntegerColumn("revision")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampzColumn("updated_at")
		allColumns               = postgres.ColumnList{IDColumn, DictionaryIDColumn, FolderIDColumn, KindColumn, TermColumn, TranslationColumn, PartOfSpeechColumn, ArticleColumn, PluralColumn, GrammarColumn, ExampleColumn, ExampleTranslationColumn, NotesColumn, SourceKeyColumn, StatusColumn, ScheduleColumn, DueAtColumn, RevisionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{DictionaryIDColumn, FolderIDColumn, KindColumn, TermColumn, TranslationColumn, PartOfSpeechColumn, ArticleColumn, PluralColumn, GrammarColumn, ExampleColumn, ExampleTranslationColumn, NotesColumn, SourceKeyColumn, StatusColumn, ScheduleColumn, DueAtColumn, RevisionColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, PartOfSpeechColumn, ArticleColumn, PluralColumn, GrammarColumn, ExampleColumn, ExampleTranslationColumn, NotesColumn, StatusColumn, RevisionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return lingvoCardsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		DictionaryID:       DictionaryIDColumn,
		FolderID:           FolderIDColumn,
		Kind:               KindColumn,
		Term:               TermColumn,
		Translation:        TranslationColumn,
		PartOfSpeech:       PartOfSpeechColumn,
		Article:            ArticleColumn,
		Plural:             PluralColumn,
		Grammar:            GrammarColumn,
		Example:            ExampleColumn,
		ExampleTranslation: ExampleTranslationColumn,
		Notes:              NotesColumn,
		SourceKey:          SourceKeyColumn,
		Status:             StatusColumn,
		Schedule:           ScheduleColumn,
		DueAt:              DueAtColumn,
		Revision:           RevisionColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
