//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LingvoFolders = newLingvoFoldersTable("public", "lingvo_folders", "")

type lingvoFoldersTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	DictionaryID postgres.ColumnString
	Name         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LingvoFoldersTable struct {
	lingvoFoldersTable

	EXCLUDED lingvoFoldersTable
}

// AS creates new LingvoFoldersTable with assigned alias
func (a LingvoFoldersTable) AS(alias string) *LingvoFoldersTable {
	return newLingvoFoldersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LingvoFoldersTable with assigned schema name
func (a LingvoFoldersTable) FromSchema(schemaName string) *LingvoFoldersTable {
	return newLingvoFoldersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LingvoFoldersTable with assigned table prefix
func (a LingvoFoldersTable) WithPrefix(prefix string) *LingvoFoldersTable {
	return newLingvoFoldersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LingvoFoldersTable with assigned table suffix
func (a LingvoFoldersTable) WithSuffix(suffix string) *LingvoFoldersTable {
	return newLingvoFoldersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLingvoFoldersTable(schemaName, tableName, alias string) *LingvoFoldersTable {
	return &LingvoFoldersTable{
		lingvoFoldersTable: newLingvoFoldersTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLingvoFoldersTableImpl("", "excluded", ""),
	}
}

func newLingvoFoldersTableImpl(schemaName, tableName, alias string) lingvoFoldersTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		DictionaryIDColumn = postgres.StringColumn("dictionary_id")
		NameColumn         = postgres.StringColumn("name")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, DictionaryIDColumn, NameColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{DictionaryIDColumn, NameColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return lingvoFoldersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		DictionaryID: DictionaryIDColumn,
		Name:         NameColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
