//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MemoroDayMedia = newMemoroDayMediaTable("public", "memoro_day_media", "")

type memoroDayMediaTable struct {
	postgres.Table

	// Columns
	UserID    postgres.ColumnString
	DayTag    postgres.ColumnString
	UploadID  postgres.ColumnString
	SizeBytes postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MemoroDayMediaTable struct {
	memoroDayMediaTable

	EXCLUDED memoroDayMediaTable
}

// AS creates new MemoroDayMediaTable with assigned alias
func (a MemoroDayMediaTable) AS(alias string) *MemoroDayMediaTable {
	return newMemoroDayMediaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MemoroDayMediaTable with assigned schema name
func (a MemoroDayMediaTable) FromSchema(schemaName string) *MemoroDayMediaTable {
	return newMemoroDayMediaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MemoroDayMediaTable with assigned table prefix
func (a MemoroDayMediaTable) WithPrefix(prefix string) *MemoroDayMediaTable {
	return newMemoroDayMediaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MemoroDayMediaTable with assigned table suffix
func (a MemoroDayMediaTable) WithSuffix(suffix string) *MemoroDayMediaTable {
	return newMemoroDayMediaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMemoroDayMediaTable(schemaName, tableName, alias string) *MemoroDayMediaTable {
	return &MemoroDayMediaTable{
		memoroDayMediaTable: newMemoroDayMediaTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newMemoroDayMediaTableImpl("", "excluded", ""),
	}
}

func newMemoroDayMediaTableImpl(schemaName, tableName, alias string) memoroDayMediaTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		DayTagColumn    = postgres.StringColumn("day_tag")
		UploadIDColumn  = postgres.StringColumn("upload_id")
		SizeBytesColumn = postgres.IntegerColumn("size_bytes")
		allColumns      = postgres.ColumnList{UserIDColumn, DayTagColumn, UploadIDColumn, SizeBytesColumn}
		mutableColumns  = postgres.ColumnList{SizeBytesColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return memoroDayMediaTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		DayTag:    DayTagColumn,
		UploadID:  UploadIDColumn,
		SizeBytes: SizeBytesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
