//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MemoroDays = newMemoroDaysTable("public", "memoro_days", "")

type memoroDaysTable struct {
	postgres.Table

	// Columns
	UserID            postgres.ColumnString
	DayTag            postgres.ColumnString
	MonthTag          postgres.ColumnString
	Nonce             postgres.ColumnString
	Ciphertext        postgres.ColumnString
	SummaryNonce      postgres.ColumnString
	SummaryCiphertext postgres.ColumnString
	Revision          postgres.ColumnInteger
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MemoroDaysTable struct {
	memoroDaysTable

	EXCLUDED memoroDaysTable
}

// AS creates new MemoroDaysTable with assigned alias
func (a MemoroDaysTable) AS(alias string) *MemoroDaysTable {
	return newMemoroDaysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MemoroDaysTable with assigned schema name
func (a MemoroDaysTable) FromSchema(schemaName string) *MemoroDaysTable {
	return newMemoroDaysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MemoroDaysTable with assigned table prefix
func (a MemoroDaysTable) WithPrefix(prefix string) *MemoroDaysTable {
	return newMemoroDaysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MemoroDaysTable with assigned table suffix
func (a MemoroDaysTable) WithSuffix(suffix string) *MemoroDaysTable {
	return newMemoroDaysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMemoroDaysTable(schemaName, tableName, alias string) *MemoroDaysTable {
	return &MemoroDaysTable{
		memoroDaysTable: newMemoroDaysTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newMemoroDaysTableImpl("", "excluded", ""),
	}
}

func newMemoroDaysTableImpl(schemaName, tableName, alias string) memoroDaysTable {
	var (
		UserIDColumn            = postgres.StringColumn("user_id")
		DayTagColumn            = postgres.StringColumn("day_tag")
		MonthTagColumn          = postgres.StringColumn("month_tag")
		NonceColumn             = postgres.StringColumn("nonce")
		CiphertextColumn        = postgres.StringColumn("ciphertext")
		SummaryNonceColumn      = postgres.StringColumn("summary_nonce")
		SummaryCiphertextColumn = postgres.StringColumn("summary_ciphertext")
		RevisionColumn          = postgres.IntegerColumn("revision")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{UserIDColumn, DayTagColumn, MonthTagColumn, NonceColumn, CiphertextColumn, SummaryNonceColumn, SummaryCiphertextColumn, RevisionColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{MonthTagColumn, NonceColumn, CiphertextColumn, SummaryNonceColumn, SummaryCiphertextColumn, RevisionColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{RevisionColumn, UpdatedAtColumn}
	)

	return memoroDaysTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:            UserIDColumn,
		DayTag:            DayTagColumn,
		MonthTag:          MonthTagColumn,
		Nonce:             NonceColumn,
		Ciphertext:        CiphertextColumn,
		SummaryNonce:      SummaryNonceColumn,
		SummaryCiphertext: SummaryCiphertextColumn,
		Revision:          RevisionColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
