//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var NodoUploadClaims = newNodoUploadClaimsTable("public", "nodo_upload_claims", "")

type nodoUploadClaimsTable struct {
	postgres.Table

	// Columns
	UploadID  postgres.ColumnString
	OwnerID   postgres.ColumnString
	ClaimedAt postgres.ColumnTimestampz
	RetiredAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type NodoUploadClaimsTable struct {
	nodoUploadClaimsTable

	EXCLUDED nodoUploadClaimsTable
}

// AS creates new NodoUploadClaimsTable with assigned alias
func (a NodoUploadClaimsTable) AS(alias string) *NodoUploadClaimsTable {
	return newNodoUploadClaimsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NodoUploadClaimsTable with assigned schema name
func (a NodoUploadClaimsTable) FromSchema(schemaName string) *NodoUploadClaimsTable {
	return newNodoUploadClaimsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NodoUploadClaimsTable with assigned table prefix
func (a NodoUploadClaimsTable) WithPrefix(prefix string) *NodoUploadClaimsTable {
	return newNodoUploadClaimsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NodoUploadClaimsTable with assigned table suffix
func (a NodoUploadClaimsTable) WithSuffix(suffix string) *NodoUploadClaimsTable {
	return newNodoUploadClaimsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNodoUploadClaimsTable(schemaName, tableName, alias string) *NodoUploadClaimsTable {
	return &NodoUploadClaimsTable{
		nodoUploadClaimsTable: newNodoUploadClaimsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newNodoUploadClaimsTableImpl("", "excluded", ""),
	}
}

func newNodoUploadClaimsTableImpl(schemaName, tableName, alias string) nodoUploadClaimsTable {
	var (
		UploadIDColumn  = postgres.StringColumn("upload_id")
		OwnerIDColumn   = postgres.StringColumn("owner_id")
		ClaimedAtColumn = postgres.TimestampzColumn("claimed_at")
		RetiredAtColumn = postgres.TimestampzColumn("retired_at")
		allColumns      = postgres.ColumnList{UploadIDColumn, OwnerIDColumn, ClaimedAtColumn, RetiredAtColumn}
		mutableColumns  = postgres.ColumnList{OwnerIDColumn, ClaimedAtColumn, RetiredAtColumn}
		defaultColumns  = postgres.ColumnList{ClaimedAtColumn}
	)

	return nodoUploadClaimsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UploadID:  UploadIDColumn,
		OwnerID:   OwnerIDColumn,
		ClaimedAt: ClaimedAtColumn,
		RetiredAt: RetiredAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
