//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PrivateRecords = newPrivateRecordsTable("public", "private_records", "")

type privateRecordsTable struct {
	postgres.Table

	// Columns
	UserID     postgres.ColumnString
	Tag        postgres.ColumnString
	Revision   postgres.ColumnInteger
	Nonce      postgres.ColumnString
	Ciphertext postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PrivateRecordsTable struct {
	privateRecordsTable

	EXCLUDED privateRecordsTable
}

// AS creates new PrivateRecordsTable with assigned alias
func (a PrivateRecordsTable) AS(alias string) *PrivateRecordsTable {
	return newPrivateRecordsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PrivateRecordsTable with assigned schema name
func (a PrivateRecordsTable) FromSchema(schemaName string) *PrivateRecordsTable {
	return newPrivateRecordsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PrivateRecordsTable with assigned table prefix
func (a PrivateRecordsTable) WithPrefix(prefix string) *PrivateRecordsTable {
	return newPrivateRecordsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PrivateRecordsTable with assigned table suffix
func (a PrivateRecordsTable) WithSuffix(suffix string) *PrivateRecordsTable {
	return newPrivateRecordsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPrivateRecordsTable(schemaName, tableName, alias string) *PrivateRecordsTable {
	return &PrivateRecordsTable{
		privateRecordsTable: newPrivateRecordsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newPrivateRecordsTableImpl("", "excluded", ""),
	}
}

func newPrivateRecordsTableImpl(schemaName, tableName, alias string) privateRecordsTable {
	var (
		UserIDColumn     = postgres.StringColumn("user_id")
		TagColumn        = postgres.StringColumn("tag")
		RevisionColumn   = postgres.IntegerColumn("revision")
		NonceColumn      = postgres.StringColumn("nonce")
		CiphertextColumn = postgres.StringColumn("ciphertext")
		allColumns       = postgres.ColumnList{UserIDColumn, TagColumn, RevisionColumn, NonceColumn, CiphertextColumn}
		mutableColumns   = postgres.ColumnList{RevisionColumn, NonceColumn, CiphertextColumn}
		defaultColumns   = postgres.ColumnList{RevisionColumn}
	)

	return privateRecordsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:     UserIDColumn,
		Tag:        TagColumn,
		Revision:   RevisionColumn,
		Nonce:      NonceColumn,
		Ciphertext: CiphertextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
