//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RegadoAlertCursors = newRegadoAlertCursorsTable("public", "regado_alert_cursors", "")

type regadoAlertCursorsTable struct {
	postgres.Table

	// Columns
	Host      postgres.ColumnString
	Sequence  postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RegadoAlertCursorsTable struct {
	regadoAlertCursorsTable

	EXCLUDED regadoAlertCursorsTable
}

// AS creates new RegadoAlertCursorsTable with assigned alias
func (a RegadoAlertCursorsTable) AS(alias string) *RegadoAlertCursorsTable {
	return newRegadoAlertCursorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RegadoAlertCursorsTable with assigned schema name
func (a RegadoAlertCursorsTable) FromSchema(schemaName string) *RegadoAlertCursorsTable {
	return newRegadoAlertCursorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RegadoAlertCursorsTable with assigned table prefix
func (a RegadoAlertCursorsTable) WithPrefix(prefix string) *RegadoAlertCursorsTable {
	return newRegadoAlertCursorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RegadoAlertCursorsTable with assigned table suffix
func (a RegadoAlertCursorsTable) WithSuffix(suffix string) *RegadoAlertCursorsTable {
	return newRegadoAlertCursorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRegadoAlertCursorsTable(schemaName, tableName, alias string) *RegadoAlertCursorsTable {
	return &RegadoAlertCursorsTable{
		regadoAlertCursorsTable: newRegadoAlertCursorsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newRegadoAlertCursorsTableImpl("", "excluded", ""),
	}
}

func newRegadoAlertCursorsTableImpl(schemaName, tableName, alias string) regadoAlertCursorsTable {
	var (
		HostColumn      = postgres.StringColumn("host")
		SequenceColumn  = postgres.IntegerColumn("sequence")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{HostColumn, SequenceColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{SequenceColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{UpdatedAtColumn}
	)

	return regadoAlertCursorsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Host:      HostColumn,
		Sequence:  SequenceColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
