//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RondoMembers = newRondoMembersTable("public", "rondo_members", "")

type rondoMembersTable struct {
	postgres.Table

	// Columns
	ServerID postgres.ColumnString
	UserID   postgres.ColumnString
	JoinedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RondoMembersTable struct {
	rondoMembersTable

	EXCLUDED rondoMembersTable
}

// AS creates new RondoMembersTable with assigned alias
func (a RondoMembersTable) AS(alias string) *RondoMembersTable {
	return newRondoMembersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RondoMembersTable with assigned schema name
func (a RondoMembersTable) FromSchema(schemaName string) *RondoMembersTable {
	return newRondoMembersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RondoMembersTable with assigned table prefix
func (a RondoMembersTable) WithPrefix(prefix string) *RondoMembersTable {
	return newRondoMembersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RondoMembersTable with assigned table suffix
func (a RondoMembersTable) WithSuffix(suffix string) *RondoMembersTable {
	return newRondoMembersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRondoMembersTable(schemaName, tableName, alias string) *RondoMembersTable {
	return &RondoMembersTable{
		rondoMembersTable: newRondoMembersTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newRondoMembersTableImpl("", "excluded", ""),
	}
}

func newRondoMembersTableImpl(schemaName, tableName, alias string) rondoMembersTable {
	var (
		ServerIDColumn = postgres.StringColumn("server_id")
		UserIDColumn   = postgres.StringColumn("user_id")
		JoinedAtColumn = postgres.TimestampzColumn("joined_at")
		allColumns     = postgres.ColumnList{ServerIDColumn, UserIDColumn, JoinedAtColumn}
		mutableColumns = postgres.ColumnList{JoinedAtColumn}
		defaultColumns = postgres.ColumnList{JoinedAtColumn}
	)

	return rondoMembersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ServerID: ServerIDColumn,
		UserID:   UserIDColumn,
		JoinedAt: JoinedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
