//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RondoServers = newRondoServersTable("public", "rondo_servers", "")

type rondoServersTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	Access      postgres.ColumnString
	OwnerID     postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RondoServersTable struct {
	rondoServersTable

	EXCLUDED rondoServersTable
}

// AS creates new RondoServersTable with assigned alias
func (a RondoServersTable) AS(alias string) *RondoServersTable {
	return newRondoServersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RondoServersTable with assigned schema name
func (a RondoServersTable) FromSchema(schemaName string) *RondoServersTable {
	return newRondoServersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RondoServersTable with assigned table prefix
func (a RondoServersTable) WithPrefix(prefix string) *RondoServersTable {
	return newRondoServersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RondoServersTable with assigned table suffix
func (a RondoServersTable) WithSuffix(suffix string) *RondoServersTable {
	return newRondoServersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRondoServersTable(schemaName, tableName, alias string) *RondoServersTable {
	return &RondoServersTable{
		rondoServersTable: newRondoServersTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newRondoServersTableImpl("", "excluded", ""),
	}
}

func newRondoServersTableImpl(schemaName, tableName, alias string) rondoServersTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		AccessColumn      = postgres.StringColumn("access")
		OwnerIDColumn     = postgres.StringColumn("owner_id")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, AccessColumn, OwnerIDColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, AccessColumn, OwnerIDColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, DescriptionColumn, CreatedAtColumn}
	)

	return rondoServersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Access:      AccessColumn,
		OwnerID:     OwnerIDColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
