//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RondoChannels = newRondoChannelsTable("public", "rondo_channels", "")

type rondoChannelsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	ServerID       postgres.ColumnString
	ConversationID postgres.ColumnString
	Name           postgres.ColumnString
	Position       postgres.ColumnInteger
	CreatedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RondoChannelsTable struct {
	rondoChannelsTable

	EXCLUDED rondoChannelsTable
}

// AS creates new RondoChannelsTable with assigned alias
func (a RondoChannelsTable) AS(alias string) *RondoChannelsTable {
	return newRondoChannelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RondoChannelsTable with assigned schema name
func (a RondoChannelsTable) FromSchema(schemaName string) *RondoChannelsTable {
	return newRondoChannelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RondoChannelsTable with assigned table prefix
func (a RondoChannelsTable) WithPrefix(prefix string) *RondoChannelsTable {
	return newRondoChannelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RondoChannelsTable with assigned table suffix
func (a RondoChannelsTable) WithSuffix(suffix string) *RondoChannelsTable {
	return newRondoChannelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRondoChannelsTable(schemaName, tableName, alias string) *RondoChannelsTable {
	return &RondoChannelsTable{
		rondoChannelsTable: newRondoChannelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newRondoChannelsTableImpl("", "excluded", ""),
	}
}

func newRondoChannelsTableImpl(schemaName, tableName, alias string) rondoChannelsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		ServerIDColumn       = postgres.StringColumn("server_id")
		ConversationIDColumn = postgres.StringColumn("conversation_id")
		NameColumn           = postgres.StringColumn("name")
		PositionColumn       = postgres.IntegerColumn("position")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		allColumns           = postgres.ColumnList{IDColumn, ServerIDColumn, ConversationIDColumn, NameColumn, PositionColumn, CreatedAtColumn}
		mutableColumns       = postgres.ColumnList{ServerIDColumn, ConversationIDColumn, NameColumn, PositionColumn, CreatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return rondoChannelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ServerID:       ServerIDColumn,
		ConversationID: ConversationIDColumn,
		Name:           NameColumn,
		Position:       PositionColumn,
		CreatedAt:      CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
