//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RondoVoiceKeys = newRondoVoiceKeysTable("public", "rondo_voice_keys", "")

type rondoVoiceKeysTable struct {
	postgres.Table

	// Columns
	ChannelID     postgres.ColumnString
	Revision      postgres.ColumnInteger
	MembershipTag postgres.ColumnString
	Envelope      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RondoVoiceKeysTable struct {
	rondoVoiceKeysTable

	EXCLUDED rondoVoiceKeysTable
}

// AS creates new RondoVoiceKeysTable with assigned alias
func (a RondoVoiceKeysTable) AS(alias string) *RondoVoiceKeysTable {
	return newRondoVoiceKeysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RondoVoiceKeysTable with assigned schema name
func (a RondoVoiceKeysTable) FromSchema(schemaName string) *RondoVoiceKeysTable {
	return newRondoVoiceKeysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RondoVoiceKeysTable with assigned table prefix
func (a RondoVoiceKeysTable) WithPrefix(prefix string) *RondoVoiceKeysTable {
	return newRondoVoiceKeysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RondoVoiceKeysTable with assigned table suffix
func (a RondoVoiceKeysTable) WithSuffix(suffix string) *RondoVoiceKeysTable {
	return newRondoVoiceKeysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRondoVoiceKeysTable(schemaName, tableName, alias string) *RondoVoiceKeysTable {
	return &RondoVoiceKeysTable{
		rondoVoiceKeysTable: newRondoVoiceKeysTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newRondoVoiceKeysTableImpl("", "excluded", ""),
	}
}

func newRondoVoiceKeysTableImpl(schemaName, tableName, alias string) rondoVoiceKeysTable {
	var (
		ChannelIDColumn     = postgres.StringColumn("channel_id")
		RevisionColumn      = postgres.IntegerColumn("revision")
		MembershipTagColumn = postgres.StringColumn("membership_tag")
		EnvelopeColumn      = postgres.StringColumn("envelope")
		allColumns          = postgres.ColumnList{ChannelIDColumn, RevisionColumn, MembershipTagColumn, EnvelopeColumn}
		mutableColumns      = postgres.ColumnList{RevisionColumn, MembershipTagColumn, EnvelopeColumn}
		defaultColumns      = postgres.ColumnList{RevisionColumn}
	)

	return rondoVoiceKeysTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ChannelID:     ChannelIDColumn,
		Revision:      RevisionColumn,
		MembershipTag: MembershipTagColumn,
		Envelope:      EnvelopeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
