//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AdminAccessCases = AdminAccessCases.FromSchema(schema)
	AdminAudit = AdminAudit.FromSchema(schema)
	FluoFollows = FluoFollows.FromSchema(schema)
	FluoNotifications = FluoNotifications.FromSchema(schema)
	FluoPostMedia = FluoPostMedia.FromSchema(schema)
	FluoPosts = FluoPosts.FromSchema(schema)
	FluoReactions = FluoReactions.FromSchema(schema)
	FluoSavedPosts = FluoSavedPosts.FromSchema(schema)
	LigoConversations = LigoConversations.FromSchema(schema)
	LigoMembers = LigoMembers.FromSchema(schema)
	LigoMessageMedia = LigoMessageMedia.FromSchema(schema)
	LigoMessageReactions = LigoMessageReactions.FromSchema(schema)
	LigoMessages = LigoMessages.FromSchema(schema)
	NodoUploadClaims = NodoUploadClaims.FromSchema(schema)
	RondoChannels = RondoChannels.FromSchema(schema)
	RondoMembers = RondoMembers.FromSchema(schema)
	RondoServers = RondoServers.FromSchema(schema)
	UserRoles = UserRoles.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
