//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AdminAudit = AdminAudit.FromSchema(schema)
	CryptoAccounts = CryptoAccounts.FromSchema(schema)
	CryptoDevices = CryptoDevices.FromSchema(schema)
	CryptoRecovery = CryptoRecovery.FromSchema(schema)
	FluoFollows = FluoFollows.FromSchema(schema)
	FluoKeyringGrants = FluoKeyringGrants.FromSchema(schema)
	FluoKeyrings = FluoKeyrings.FromSchema(schema)
	FluoNotifications = FluoNotifications.FromSchema(schema)
	FluoPostMedia = FluoPostMedia.FromSchema(schema)
	FluoPosts = FluoPosts.FromSchema(schema)
	FluoProfileImages = FluoProfileImages.FromSchema(schema)
	FluoProfiles = FluoProfiles.FromSchema(schema)
	FluoReactions = FluoReactions.FromSchema(schema)
	FluoSavedPosts = FluoSavedPosts.FromSchema(schema)
	FluoSettings = FluoSettings.FromSchema(schema)
	LigoConversations = LigoConversations.FromSchema(schema)
	LigoMembers = LigoMembers.FromSchema(schema)
	LigoMessageMedia = LigoMessageMedia.FromSchema(schema)
	LigoMessageReactions = LigoMessageReactions.FromSchema(schema)
	LigoMessages = LigoMessages.FromSchema(schema)
	MemoroDayMedia = MemoroDayMedia.FromSchema(schema)
	MemoroDays = MemoroDays.FromSchema(schema)
	NodoUploadClaims = NodoUploadClaims.FromSchema(schema)
	PrivateRecords = PrivateRecords.FromSchema(schema)
	RegadoAlertCursors = RegadoAlertCursors.FromSchema(schema)
	RondoChannels = RondoChannels.FromSchema(schema)
	RondoMembers = RondoMembers.FromSchema(schema)
	RondoServers = RondoServers.FromSchema(schema)
	RondoVoiceKeys = RondoVoiceKeys.FromSchema(schema)
	UserRoles = UserRoles.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
