//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	KeycloakSub    postgres.ColumnString
	Username       postgres.ColumnString
	DisplayName    postgres.ColumnString
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz
	DisabledAt     postgres.ColumnTimestampz
	DisabledReason postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		KeycloakSubColumn    = postgres.StringColumn("keycloak_sub")
		UsernameColumn       = postgres.StringColumn("username")
		DisplayNameColumn    = postgres.StringColumn("display_name")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		DisabledAtColumn     = postgres.TimestampzColumn("disabled_at")
		DisabledReasonColumn = postgres.StringColumn("disabled_reason")
		allColumns           = postgres.ColumnList{IDColumn, KeycloakSubColumn, UsernameColumn, DisplayNameColumn, CreatedAtColumn, UpdatedAtColumn, DisabledAtColumn, DisabledReasonColumn}
		mutableColumns       = postgres.ColumnList{KeycloakSubColumn, UsernameColumn, DisplayNameColumn, CreatedAtColumn, UpdatedAtColumn, DisabledAtColumn, DisabledReasonColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DisabledReasonColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		KeycloakSub:    KeycloakSubColumn,
		Username:       UsernameColumn,
		DisplayName:    DisplayNameColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		DisabledAt:     DisabledAtColumn,
		DisabledReason: DisabledReasonColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
