// Generated by scripts/sync-theme.mjs from the shared theme catalog
// Applies persisted appearance to Keycloak's native credential forms before paint
(() => {
  const keys = {"modeStorageKey":"kaordo.color-mode","themeStorageKey":"kaordo.theme","identityModeParameter":"kaordo_mode","identityThemeParameter":"kaordo_theme"};
  const modeKey = keys.modeStorageKey;
  const themeKey = keys.themeStorageKey;
  const themes = ["deep-purple","discord","leadgen","lara","damon","party-rock","japan-blues"];
  const systemDark = window.matchMedia('(prefers-color-scheme: dark)');
  const url = new URL(window.location.href);
  let preference = readPreference(modeKey);
  let savedTheme = readPreference(themeKey);

  const incomingMode = url.searchParams.get(keys.identityModeParameter);
  const incomingTheme = url.searchParams.get(keys.identityThemeParameter);
  if (['light', 'dark', 'system'].includes(incomingMode)) {
    preference = incomingMode;
    persistPreference(modeKey, preference);
  }
  if (themes.includes(incomingTheme)) {
    savedTheme = incomingTheme;
    persistPreference(themeKey, savedTheme);
  }
  if (url.searchParams.has(keys.identityModeParameter) || url.searchParams.has(keys.identityThemeParameter)) {
    url.searchParams.delete(keys.identityModeParameter);
    url.searchParams.delete(keys.identityThemeParameter);
    window.history.replaceState(window.history.state, '', url.href);
  }

  function readPreference(key) {
    try { return localStorage.getItem(key); } catch { return null; }
  }
  function persistPreference(key, value) {
    try { localStorage.setItem(key, value); } catch { /* The current form still uses the supplied preference */ }
  }
  function applyAppearance() {
    const dark = preference === 'dark' || (preference !== 'light' && systemDark.matches);
    document.documentElement.classList.toggle('dark', dark);
    document.documentElement.style.colorScheme = dark ? 'dark' : 'light';
    document.documentElement.dataset.theme = themes.includes(savedTheme) ? savedTheme : themes[0];
  }
  applyAppearance();
  systemDark.addEventListener('change', applyAppearance);
  window.addEventListener('storage', (event) => {
    if (event.key === modeKey || event.key === null) preference = readPreference(modeKey);
    if (event.key === themeKey || event.key === null) savedTheme = readPreference(themeKey);
    if (event.key === modeKey || event.key === themeKey || event.key === null) applyAppearance();
  });
})();
