// Generates Keycloak palettes and preference handling from the shared theme catalog
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const source = resolve(root, 'packages/ui/src/lib/themes');
const target = resolve(root, 'deploy/keycloak/themes/kaordo/login/resources');
const catalog = JSON.parse(await readFile(resolve(source, 'catalog.json'), 'utf8'));
const preferences = JSON.parse(await readFile(resolve(source, 'preferences.json'), 'utf8'));
const palettes = await Promise.all(
	catalog.map(({ id }) => readFile(resolve(source, `${id}.css`), 'utf8'))
);
const controls = await readFile(resolve(source, 'controls.css'), 'utf8');
await writeFile(
	resolve(target, 'css/deep-purple.css'),
	'/* Generated by scripts/sync-theme.mjs from packages/ui/src/lib/themes/deep-purple.css */\n' +
		palettes[0]
);
await writeFile(
	resolve(target, 'css/themes.css'),
	'/* Generated by scripts/sync-theme.mjs from packages/ui/src/lib/themes */\n' +
		palettes.slice(1).join('\n') +
		'\n' +
		controls
);
await writeFile(
	resolve(target, 'js/theme.js'),
	`// Generated by scripts/sync-theme.mjs from the shared theme catalog
// Applies persisted appearance to Keycloak's native credential forms before paint
(() => {
  const keys = ${JSON.stringify(preferences)};
  const modeKey = keys.modeStorageKey;
  const themeKey = keys.themeStorageKey;
  const themes = ${JSON.stringify(catalog.map(({ id }) => id))};
  const systemDark = window.matchMedia('(prefers-color-scheme: dark)');
  const url = new URL(window.location.href);
  let preference = readPreference(modeKey);
  let savedTheme = readPreference(themeKey);

  const incomingMode = url.searchParams.get(keys.identityModeParameter);
  const incomingTheme = url.searchParams.get(keys.identityThemeParameter);
  if (['light', 'dark', 'system'].includes(incomingMode)) {
    preference = incomingMode;
    persistPreference(modeKey, preference);
  }
  if (themes.includes(incomingTheme)) {
    savedTheme = incomingTheme;
    persistPreference(themeKey, savedTheme);
  }
  if (url.searchParams.has(keys.identityModeParameter) || url.searchParams.has(keys.identityThemeParameter)) {
    url.searchParams.delete(keys.identityModeParameter);
    url.searchParams.delete(keys.identityThemeParameter);
    window.history.replaceState(window.history.state, '', url.href);
  }

  function readPreference(key) {
    try { return localStorage.getItem(key); } catch { return null; }
  }
  function persistPreference(key, value) {
    try { localStorage.setItem(key, value); } catch { /* The current form still uses the supplied preference */ }
  }
  function applyAppearance() {
    const dark = preference === 'dark' || (preference !== 'light' && systemDark.matches);
    document.documentElement.classList.toggle('dark', dark);
    document.documentElement.style.colorScheme = dark ? 'dark' : 'light';
    document.documentElement.dataset.theme = themes.includes(savedTheme) ? savedTheme : themes[0];
  }
  applyAppearance();
  systemDark.addEventListener('change', applyAppearance);
  window.addEventListener('storage', (event) => {
    if (event.key === modeKey || event.key === null) preference = readPreference(modeKey);
    if (event.key === themeKey || event.key === null) savedTheme = readPreference(themeKey);
    if (event.key === modeKey || event.key === themeKey || event.key === null) applyAppearance();
  });
})();
`
);
