// Copies the canonical palette into Keycloak's independently served identity theme
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const palette = await readFile(resolve(root, 'packages/ui/src/lib/themes/deep-purple.css'), 'utf8');
await writeFile(
  resolve(root, 'deploy/keycloak/themes/kaordo/login/resources/css/deep-purple.css'),
  '/* Generated by scripts/sync-theme.mjs from packages/ui/src/lib/themes/deep-purple.css */\n' + palette,
);
